// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: filelister/v1/filelister.proto

package filelisterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/apipb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	HostService   uint32                 `protobuf:"varint,2,opt,name=host_service,json=hostService,proto3" json:"host_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_filelister_v1_filelister_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filelister_v1_filelister_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_filelister_v1_filelister_proto_rawDescGZIP(), []int{0}
}

func (x *FileListRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *FileListRequest) GetHostService() uint32 {
	if x != nil {
		return x.HostService
	}
	return 0
}

type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         []string               `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_filelister_v1_filelister_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filelister_v1_filelister_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_filelister_v1_filelister_proto_rawDescGZIP(), []int{1}
}

func (x *FileListResponse) GetEntry() []string {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *FileListResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type HostServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostService   uint32                 `protobuf:"varint,1,opt,name=host_service,json=hostService,proto3" json:"host_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostServiceRequest) Reset() {
	*x = HostServiceRequest{}
	mi := &file_filelister_v1_filelister_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostServiceRequest) ProtoMessage() {}

func (x *HostServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filelister_v1_filelister_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostServiceRequest.ProtoReflect.Descriptor instead.
func (*HostServiceRequest) Descriptor() ([]byte, []int) {
	return file_filelister_v1_filelister_proto_rawDescGZIP(), []int{2}
}

func (x *HostServiceRequest) GetHostService() uint32 {
	if x != nil {
		return x.HostService
	}
	return 0
}

type HostServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostServiceResponse) Reset() {
	*x = HostServiceResponse{}
	mi := &file_filelister_v1_filelister_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostServiceResponse) ProtoMessage() {}

func (x *HostServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filelister_v1_filelister_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostServiceResponse.ProtoReflect.Descriptor instead.
func (*HostServiceResponse) Descriptor() ([]byte, []int) {
	return file_filelister_v1_filelister_proto_rawDescGZIP(), []int{3}
}

func (x *HostServiceResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HostServiceResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_filelister_v1_filelister_proto protoreflect.FileDescriptor

const file_filelister_v1_filelister_proto_rawDesc = "" +
	"\n" +
	"\x1efilelister/v1/filelister.proto\x12\rfilelister.v1\x1a\x19google/protobuf/api.proto\"F\n" +
	"\x0fFileListRequest\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12!\n" +
	"\fhost_service\x18\x02 \x01(\rR\vhostService\"M\n" +
	"\x10FileListResponse\x12\x14\n" +
	"\x05entry\x18\x01 \x03(\tR\x05entry\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"7\n" +
	"\x12HostServiceRequest\x12!\n" +
	"\fhost_service\x18\x01 \x01(\rR\vhostService\"W\n" +
	"\x13HostServiceResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xb5\x01\n" +
	"\n" +
	"FileLister\x12^\n" +
	"\x15EstablishHostServices\x12!.filelister.v1.HostServiceRequest\x1a\".filelister.v1.HostServiceResponse\x12G\n" +
	"\x04List\x12\x1e.filelister.v1.FileListRequest\x1a\x1f.filelister.v1.FileListResponseB\xc8\x01\n" +
	"\x11com.filelister.v1B\x0fFilelisterProtoP\x01ZMgithub.com/bmj2728/HostServiceTest/shared/protogen/filelister/v1;filelisterv1\xa2\x02\x03FXX\xaa\x02\rFilelister.V1\xca\x02\rFilelister\\V1\xe2\x02\x19Filelister\\V1\\GPBMetadata\xea\x02\x0eFilelister::V1b\x06proto3"

var (
	file_filelister_v1_filelister_proto_rawDescOnce sync.Once
	file_filelister_v1_filelister_proto_rawDescData []byte
)

func file_filelister_v1_filelister_proto_rawDescGZIP() []byte {
	file_filelister_v1_filelister_proto_rawDescOnce.Do(func() {
		file_filelister_v1_filelister_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filelister_v1_filelister_proto_rawDesc), len(file_filelister_v1_filelister_proto_rawDesc)))
	})
	return file_filelister_v1_filelister_proto_rawDescData
}

var file_filelister_v1_filelister_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_filelister_v1_filelister_proto_goTypes = []any{
	(*FileListRequest)(nil),     // 0: filelister.v1.FileListRequest
	(*FileListResponse)(nil),    // 1: filelister.v1.FileListResponse
	(*HostServiceRequest)(nil),  // 2: filelister.v1.HostServiceRequest
	(*HostServiceResponse)(nil), // 3: filelister.v1.HostServiceResponse
}
var file_filelister_v1_filelister_proto_depIdxs = []int32{
	2, // 0: filelister.v1.FileLister.EstablishHostServices:input_type -> filelister.v1.HostServiceRequest
	0, // 1: filelister.v1.FileLister.List:input_type -> filelister.v1.FileListRequest
	3, // 2: filelister.v1.FileLister.EstablishHostServices:output_type -> filelister.v1.HostServiceResponse
	1, // 3: filelister.v1.FileLister.List:output_type -> filelister.v1.FileListResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filelister_v1_filelister_proto_init() }
func file_filelister_v1_filelister_proto_init() {
	if File_filelister_v1_filelister_proto != nil {
		return
	}
	file_filelister_v1_filelister_proto_msgTypes[1].OneofWrappers = []any{}
	file_filelister_v1_filelister_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filelister_v1_filelister_proto_rawDesc), len(file_filelister_v1_filelister_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filelister_v1_filelister_proto_goTypes,
		DependencyIndexes: file_filelister_v1_filelister_proto_depIdxs,
		MessageInfos:      file_filelister_v1_filelister_proto_msgTypes,
	}.Build()
	File_filelister_v1_filelister_proto = out.File
	file_filelister_v1_filelister_proto_goTypes = nil
	file_filelister_v1_filelister_proto_depIdxs = nil
}
