# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from filelister.v1 import filelister_pb2 as filelister_dot_v1_dot_filelister__pb2


class FileListerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstablishHostServices = channel.unary_unary(
                '/filelister.v1.FileLister/EstablishHostServices',
                request_serializer=filelister_dot_v1_dot_filelister__pb2.HostServiceRequest.SerializeToString,
                response_deserializer=filelister_dot_v1_dot_filelister__pb2.HostServiceResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/filelister.v1.FileLister/List',
                request_serializer=filelister_dot_v1_dot_filelister__pb2.FileListRequest.SerializeToString,
                response_deserializer=filelister_dot_v1_dot_filelister__pb2.FileListResponse.FromString,
                _registered_method=True)


class FileListerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EstablishHostServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileListerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstablishHostServices': grpc.unary_unary_rpc_method_handler(
                    servicer.EstablishHostServices,
                    request_deserializer=filelister_dot_v1_dot_filelister__pb2.HostServiceRequest.FromString,
                    response_serializer=filelister_dot_v1_dot_filelister__pb2.HostServiceResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=filelister_dot_v1_dot_filelister__pb2.FileListRequest.FromString,
                    response_serializer=filelister_dot_v1_dot_filelister__pb2.FileListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filelister.v1.FileLister', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('filelister.v1.FileLister', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileLister(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EstablishHostServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filelister.v1.FileLister/EstablishHostServices',
            filelister_dot_v1_dot_filelister__pb2.HostServiceRequest.SerializeToString,
            filelister_dot_v1_dot_filelister__pb2.HostServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filelister.v1.FileLister/List',
            filelister_dot_v1_dot_filelister__pb2.FileListRequest.SerializeToString,
            filelister_dot_v1_dot_filelister__pb2.FileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
