# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filelister/v1/filelister.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'filelister/v1/filelister.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import api_pb2 as google_dot_protobuf_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66ilelister/v1/filelister.proto\x12\rfilelister.v1\x1a\x19google/protobuf/api.proto\"c\n\x0f\x46ileListRequest\x12\x19\n\x08root_dir\x18\x01 \x01(\tR\x07rootDir\x12\x12\n\x04path\x18\x02 \x01(\tR\x04path\x12!\n\x0chost_service\x18\x03 \x01(\rR\x0bhostService\"M\n\x10\x46ileListResponse\x12\x14\n\x05\x65ntry\x18\x01 \x03(\tR\x05\x65ntry\x12\x19\n\x05\x65rror\x18\x02 \x01(\tH\x00R\x05\x65rror\x88\x01\x01\x42\x08\n\x06_error\"7\n\x12HostServiceRequest\x12!\n\x0chost_service\x18\x01 \x01(\rR\x0bhostService\"W\n\x13HostServiceResponse\x12\x1b\n\tclient_id\x18\x01 \x01(\tR\x08\x63lientId\x12\x19\n\x05\x65rror\x18\x02 \x01(\tH\x00R\x05\x65rror\x88\x01\x01\x42\x08\n\x06_error2\xb5\x01\n\nFileLister\x12^\n\x15\x45stablishHostServices\x12!.filelister.v1.HostServiceRequest\x1a\".filelister.v1.HostServiceResponse\x12G\n\x04List\x12\x1e.filelister.v1.FileListRequest\x1a\x1f.filelister.v1.FileListResponseB\xc8\x01\n\x11\x63om.filelister.v1B\x0f\x46ilelisterProtoP\x01ZMgithub.com/bmj2728/HostServiceTest/shared/protogen/filelister/v1;filelisterv1\xa2\x02\x03\x46XX\xaa\x02\rFilelister.V1\xca\x02\rFilelister\\V1\xe2\x02\x19\x46ilelister\\V1\\GPBMetadata\xea\x02\x0e\x46ilelister::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filelister.v1.filelister_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.filelister.v1B\017FilelisterProtoP\001ZMgithub.com/bmj2728/HostServiceTest/shared/protogen/filelister/v1;filelisterv1\242\002\003FXX\252\002\rFilelister.V1\312\002\rFilelister\\V1\342\002\031Filelister\\V1\\GPBMetadata\352\002\016Filelister::V1'
  _globals['_FILELISTREQUEST']._serialized_start=76
  _globals['_FILELISTREQUEST']._serialized_end=175
  _globals['_FILELISTRESPONSE']._serialized_start=177
  _globals['_FILELISTRESPONSE']._serialized_end=254
  _globals['_HOSTSERVICEREQUEST']._serialized_start=256
  _globals['_HOSTSERVICEREQUEST']._serialized_end=311
  _globals['_HOSTSERVICERESPONSE']._serialized_start=313
  _globals['_HOSTSERVICERESPONSE']._serialized_end=400
  _globals['_FILELISTER']._serialized_start=403
  _globals['_FILELISTER']._serialized_end=584
# @@protoc_insertion_point(module_scope)
