// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: hostserve/v1/hostserve.proto

package hostservev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenFileMode int32

const (
	OpenFileMode_OPEN_FILE_MODE_UNSPECIFIED OpenFileMode = 0
	// Read modes
	OpenFileMode_READ_ONLY OpenFileMode = 1 // O_RDONLY
	// Write modes
	OpenFileMode_WRITE_TRUNCATE  OpenFileMode = 2 // O_WRONLY|O_CREATE|O_TRUNC (like os.Create)
	OpenFileMode_WRITE_APPEND    OpenFileMode = 3 // O_WRONLY|O_CREATE|O_APPEND
	OpenFileMode_WRITE_EXCLUSIVE OpenFileMode = 4 // O_WRONLY|O_CREATE|O_EXCL (fail if exists)
	// Read/Write modes
	OpenFileMode_READ_WRITE          OpenFileMode = 5 // O_RDWR
	OpenFileMode_READ_WRITE_CREATE   OpenFileMode = 6 // O_RDWR|O_CREATE
	OpenFileMode_READ_WRITE_TRUNCATE OpenFileMode = 7 // O_RDWR|O_CREATE|O_TRUNC
	OpenFileMode_READ_WRITE_APPEND   OpenFileMode = 8 // O_RDWR|O_CREATE|O_APPEND
)

// Enum value maps for OpenFileMode.
var (
	OpenFileMode_name = map[int32]string{
		0: "OPEN_FILE_MODE_UNSPECIFIED",
		1: "READ_ONLY",
		2: "WRITE_TRUNCATE",
		3: "WRITE_APPEND",
		4: "WRITE_EXCLUSIVE",
		5: "READ_WRITE",
		6: "READ_WRITE_CREATE",
		7: "READ_WRITE_TRUNCATE",
		8: "READ_WRITE_APPEND",
	}
	OpenFileMode_value = map[string]int32{
		"OPEN_FILE_MODE_UNSPECIFIED": 0,
		"READ_ONLY":                  1,
		"WRITE_TRUNCATE":             2,
		"WRITE_APPEND":               3,
		"WRITE_EXCLUSIVE":            4,
		"READ_WRITE":                 5,
		"READ_WRITE_CREATE":          6,
		"READ_WRITE_TRUNCATE":        7,
		"READ_WRITE_APPEND":          8,
	}
)

func (x OpenFileMode) Enum() *OpenFileMode {
	p := new(OpenFileMode)
	*p = x
	return p
}

func (x OpenFileMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenFileMode) Descriptor() protoreflect.EnumDescriptor {
	return file_hostserve_v1_hostserve_proto_enumTypes[0].Descriptor()
}

func (OpenFileMode) Type() protoreflect.EnumType {
	return &file_hostserve_v1_hostserve_proto_enumTypes[0]
}

func (x OpenFileMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenFileMode.Descriptor instead.
func (OpenFileMode) EnumDescriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{0}
}

// DirEntry represents the basic dir entry data
type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{0}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	IsDir         bool                   `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type ReadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootDir       string                 `protobuf:"bytes,1,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{3}
}

func (x *ReadDirRequest) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *ReadDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{4}
}

func (x *ReadDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReadDirResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []byte                 `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileResponse) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *ReadFileResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Perm          uint32                 `protobuf:"varint,3,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteFileRequest) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{8}
}

func (x *WriteFileResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{9}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *FileInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{10}
}

func (x *StatResponse) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *StatResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootDir       string                 `protobuf:"bytes,1,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	OldName       string                 `protobuf:"bytes,2,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{11}
}

func (x *RenameRequest) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *RenameRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{12}
}

func (x *RenameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootDir       string                 `protobuf:"bytes,1,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Perm          uint32                 `protobuf:"varint,3,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{13}
}

func (x *MkdirRequest) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *MkdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MkdirRequest) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{14}
}

func (x *MkdirResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type MkdirAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootDir       string                 `protobuf:"bytes,1,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Perm          uint32                 `protobuf:"varint,3,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirAllRequest) Reset() {
	*x = MkdirAllRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirAllRequest) ProtoMessage() {}

func (x *MkdirAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirAllRequest.ProtoReflect.Descriptor instead.
func (*MkdirAllRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{15}
}

func (x *MkdirAllRequest) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *MkdirAllRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirAllRequest) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

type MkdirAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirAllResponse) Reset() {
	*x = MkdirAllResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirAllResponse) ProtoMessage() {}

func (x *MkdirAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirAllResponse.ProtoReflect.Descriptor instead.
func (*MkdirAllResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{16}
}

func (x *MkdirAllResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type MkdirTempRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootDir       string                 `protobuf:"bytes,1,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirTempRequest) Reset() {
	*x = MkdirTempRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirTempRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirTempRequest) ProtoMessage() {}

func (x *MkdirTempRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirTempRequest.ProtoReflect.Descriptor instead.
func (*MkdirTempRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{17}
}

func (x *MkdirTempRequest) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *MkdirTempRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type MkdirTempResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirTempResponse) Reset() {
	*x = MkdirTempResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirTempResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirTempResponse) ProtoMessage() {}

func (x *MkdirTempResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirTempResponse.ProtoReflect.Descriptor instead.
func (*MkdirTempResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{18}
}

func (x *MkdirTempResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirTempResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCreateRequest) Reset() {
	*x = FileCreateRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreateRequest) ProtoMessage() {}

func (x *FileCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCreateRequest.ProtoReflect.Descriptor instead.
func (*FileCreateRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{19}
}

func (x *FileCreateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCreateResponse) Reset() {
	*x = FileCreateResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreateResponse) ProtoMessage() {}

func (x *FileCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCreateResponse.ProtoReflect.Descriptor instead.
func (*FileCreateResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{20}
}

func (x *FileCreateResponse) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *FileCreateResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileCreateTempRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootDir       string                 `protobuf:"bytes,1,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCreateTempRequest) Reset() {
	*x = FileCreateTempRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCreateTempRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreateTempRequest) ProtoMessage() {}

func (x *FileCreateTempRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCreateTempRequest.ProtoReflect.Descriptor instead.
func (*FileCreateTempRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{21}
}

func (x *FileCreateTempRequest) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *FileCreateTempRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type FileCreateTempResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCreateTempResponse) Reset() {
	*x = FileCreateTempResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCreateTempResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreateTempResponse) ProtoMessage() {}

func (x *FileCreateTempResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCreateTempResponse.ProtoReflect.Descriptor instead.
func (*FileCreateTempResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{22}
}

func (x *FileCreateTempResponse) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *FileCreateTempResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          OpenFileMode           `protobuf:"varint,2,opt,name=mode,proto3,enum=hostserve.v1.OpenFileMode" json:"mode,omitempty"`
	Perm          uint32                 `protobuf:"varint,3,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOpenRequest) Reset() {
	*x = FileOpenRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOpenRequest) ProtoMessage() {}

func (x *FileOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOpenRequest.ProtoReflect.Descriptor instead.
func (*FileOpenRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{23}
}

func (x *FileOpenRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileOpenRequest) GetMode() OpenFileMode {
	if x != nil {
		return x.Mode
	}
	return OpenFileMode_OPEN_FILE_MODE_UNSPECIFIED
}

func (x *FileOpenRequest) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

type FileOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOpenResponse) Reset() {
	*x = FileOpenResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOpenResponse) ProtoMessage() {}

func (x *FileOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOpenResponse.ProtoReflect.Descriptor instead.
func (*FileOpenResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{24}
}

func (x *FileOpenResponse) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *FileOpenResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileOpenResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatRequest) Reset() {
	*x = FileStatRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatRequest) ProtoMessage() {}

func (x *FileStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatRequest.ProtoReflect.Descriptor instead.
func (*FileStatRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{25}
}

func (x *FileStatRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type FileStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *FileInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatResponse) Reset() {
	*x = FileStatResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatResponse) ProtoMessage() {}

func (x *FileStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatResponse.ProtoReflect.Descriptor instead.
func (*FileStatResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{26}
}

func (x *FileStatResponse) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *FileStatResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileSeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Whence        uint32                 `protobuf:"varint,3,opt,name=whence,proto3" json:"whence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSeekRequest) Reset() {
	*x = FileSeekRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSeekRequest) ProtoMessage() {}

func (x *FileSeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSeekRequest.ProtoReflect.Descriptor instead.
func (*FileSeekRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{27}
}

func (x *FileSeekRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *FileSeekRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileSeekRequest) GetWhence() uint32 {
	if x != nil {
		return x.Whence
	}
	return 0
}

type FileSeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewOffset     uint64                 `protobuf:"varint,1,opt,name=new_offset,json=newOffset,proto3" json:"new_offset,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSeekResponse) Reset() {
	*x = FileSeekResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSeekResponse) ProtoMessage() {}

func (x *FileSeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSeekResponse.ProtoReflect.Descriptor instead.
func (*FileSeekResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{28}
}

func (x *FileSeekResponse) GetNewOffset() uint64 {
	if x != nil {
		return x.NewOffset
	}
	return 0
}

func (x *FileSeekResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSyncRequest) Reset() {
	*x = FileSyncRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSyncRequest) ProtoMessage() {}

func (x *FileSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSyncRequest.ProtoReflect.Descriptor instead.
func (*FileSyncRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{29}
}

func (x *FileSyncRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type FileSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSyncResponse) Reset() {
	*x = FileSyncResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSyncResponse) ProtoMessage() {}

func (x *FileSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSyncResponse.ProtoReflect.Descriptor instead.
func (*FileSyncResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{30}
}

func (x *FileSyncResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCloseRequest) Reset() {
	*x = FileCloseRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCloseRequest) ProtoMessage() {}

func (x *FileCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCloseRequest.ProtoReflect.Descriptor instead.
func (*FileCloseRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{31}
}

func (x *FileCloseRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type FileCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCloseResponse) Reset() {
	*x = FileCloseResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCloseResponse) ProtoMessage() {}

func (x *FileCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCloseResponse.ProtoReflect.Descriptor instead.
func (*FileCloseResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{32}
}

func (x *FileCloseResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileTruncateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTruncateRequest) Reset() {
	*x = FileTruncateRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTruncateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTruncateRequest) ProtoMessage() {}

func (x *FileTruncateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTruncateRequest.ProtoReflect.Descriptor instead.
func (*FileTruncateRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{33}
}

func (x *FileTruncateRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *FileTruncateRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileTruncateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTruncateResponse) Reset() {
	*x = FileTruncateResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTruncateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTruncateResponse) ProtoMessage() {}

func (x *FileTruncateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTruncateResponse.ProtoReflect.Descriptor instead.
func (*FileTruncateResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{34}
}

func (x *FileTruncateResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	ChunkSize     uint32                 `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadRequest) Reset() {
	*x = FileReadRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadRequest) ProtoMessage() {}

func (x *FileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadRequest.ProtoReflect.Descriptor instead.
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{35}
}

func (x *FileReadRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *FileReadRequest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type FileReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *FileChunk             `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadResponse) Reset() {
	*x = FileReadResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResponse) ProtoMessage() {}

func (x *FileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadResponse.ProtoReflect.Descriptor instead.
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{36}
}

func (x *FileReadResponse) GetChunk() *FileChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FileReadResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type FileWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Chunk         *FileChunk             `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteRequest) Reset() {
	*x = FileWriteRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteRequest) ProtoMessage() {}

func (x *FileWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteRequest.ProtoReflect.Descriptor instead.
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{37}
}

func (x *FileWriteRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *FileWriteRequest) GetChunk() *FileChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type FileWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint32                 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteResponse) Reset() {
	*x = FileWriteResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteResponse) ProtoMessage() {}

func (x *FileWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteResponse.ProtoReflect.Descriptor instead.
func (*FileWriteResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{38}
}

func (x *FileWriteResponse) GetBytesWritten() uint32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *FileWriteResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvRequest) Reset() {
	*x = GetEnvRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvRequest) ProtoMessage() {}

func (x *GetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvRequest.ProtoReflect.Descriptor instead.
func (*GetEnvRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{39}
}

func (x *GetEnvRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetEnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvResponse) Reset() {
	*x = GetEnvResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvResponse) ProtoMessage() {}

func (x *GetEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvResponse.ProtoReflect.Descriptor instead.
func (*GetEnvResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{40}
}

func (x *GetEnvResponse) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *GetEnvResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type TempDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempDirRequest) Reset() {
	*x = TempDirRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempDirRequest) ProtoMessage() {}

func (x *TempDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempDirRequest.ProtoReflect.Descriptor instead.
func (*TempDirRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{41}
}

type TempDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempDirResponse) Reset() {
	*x = TempDirResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempDirResponse) ProtoMessage() {}

func (x *TempDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempDirResponse.ProtoReflect.Descriptor instead.
func (*TempDirResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{42}
}

func (x *TempDirResponse) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *TempDirResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type UserCacheDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCacheDirRequest) Reset() {
	*x = UserCacheDirRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCacheDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCacheDirRequest) ProtoMessage() {}

func (x *UserCacheDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCacheDirRequest.ProtoReflect.Descriptor instead.
func (*UserCacheDirRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{43}
}

type UserCacheDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCacheDirResponse) Reset() {
	*x = UserCacheDirResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCacheDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCacheDirResponse) ProtoMessage() {}

func (x *UserCacheDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCacheDirResponse.ProtoReflect.Descriptor instead.
func (*UserCacheDirResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{44}
}

func (x *UserCacheDirResponse) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *UserCacheDirResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type UserConfigDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConfigDirRequest) Reset() {
	*x = UserConfigDirRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConfigDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConfigDirRequest) ProtoMessage() {}

func (x *UserConfigDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConfigDirRequest.ProtoReflect.Descriptor instead.
func (*UserConfigDirRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{45}
}

type UserConfigDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConfigDirResponse) Reset() {
	*x = UserConfigDirResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConfigDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConfigDirResponse) ProtoMessage() {}

func (x *UserConfigDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConfigDirResponse.ProtoReflect.Descriptor instead.
func (*UserConfigDirResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{46}
}

func (x *UserConfigDirResponse) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *UserConfigDirResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type UserHomeDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserHomeDirRequest) Reset() {
	*x = UserHomeDirRequest{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHomeDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHomeDirRequest) ProtoMessage() {}

func (x *UserHomeDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHomeDirRequest.ProtoReflect.Descriptor instead.
func (*UserHomeDirRequest) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{47}
}

type UserHomeDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserHomeDirResponse) Reset() {
	*x = UserHomeDirResponse{}
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHomeDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHomeDirResponse) ProtoMessage() {}

func (x *UserHomeDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostserve_v1_hostserve_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHomeDirResponse.ProtoReflect.Descriptor instead.
func (*UserHomeDirResponse) Descriptor() ([]byte, []int) {
	return file_hostserve_v1_hostserve_proto_rawDescGZIP(), []int{48}
}

func (x *UserHomeDirResponse) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *UserHomeDirResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_hostserve_v1_hostserve_proto protoreflect.FileDescriptor

const file_hostserve_v1_hostserve_proto_rawDesc = "" +
	"\n" +
	"\x1chostserve/v1/hostserve.proto\x12\fhostserve.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\"R\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\"\x94\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x15\n" +
	"\x06is_dir\x18\x05 \x01(\bR\x05isDir\"?\n" +
	"\x0eReadDirRequest\x12\x19\n" +
	"\broot_dir\x18\x01 \x01(\tR\arootDir\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"h\n" +
	"\x0fReadDirResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.hostserve.v1.DirEntryR\aentries\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"S\n" +
	"\x10ReadFileResponse\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\fR\bcontents\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"N\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04perm\x18\x03 \x01(\rR\x04perm\"8\n" +
	"\x11WriteFileResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"_\n" +
	"\fStatResponse\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.hostserve.v1.FileInfoR\x04info\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"`\n" +
	"\rRenameRequest\x12\x19\n" +
	"\broot_dir\x18\x01 \x01(\tR\arootDir\x12\x19\n" +
	"\bold_name\x18\x02 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"&\n" +
	"\x0eRenameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"Q\n" +
	"\fMkdirRequest\x12\x19\n" +
	"\broot_dir\x18\x01 \x01(\tR\arootDir\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04perm\x18\x03 \x01(\rR\x04perm\"4\n" +
	"\rMkdirResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"T\n" +
	"\x0fMkdirAllRequest\x12\x19\n" +
	"\broot_dir\x18\x01 \x01(\tR\arootDir\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04perm\x18\x03 \x01(\rR\x04perm\"7\n" +
	"\x10MkdirAllResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"G\n" +
	"\x10MkdirTempRequest\x12\x19\n" +
	"\broot_dir\x18\x01 \x01(\tR\arootDir\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\"L\n" +
	"\x11MkdirTempResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"'\n" +
	"\x11FileCreateRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"Q\n" +
	"\x12FileCreateResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"L\n" +
	"\x15FileCreateTempRequest\x12\x19\n" +
	"\broot_dir\x18\x01 \x01(\tR\arootDir\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\"U\n" +
	"\x16FileCreateTempResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"i\n" +
	"\x0fFileOpenRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12.\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1a.hostserve.v1.OpenFileModeR\x04mode\x12\x12\n" +
	"\x04perm\x18\x03 \x01(\rR\x04perm\"c\n" +
	"\x10FileOpenResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\")\n" +
	"\x0fFileStatRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"c\n" +
	"\x10FileStatResponse\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.hostserve.v1.FileInfoR\x04info\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"Y\n" +
	"\x0fFileSeekRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06whence\x18\x03 \x01(\rR\x06whence\"V\n" +
	"\x10FileSeekResponse\x12\x1d\n" +
	"\n" +
	"new_offset\x18\x01 \x01(\x04R\tnewOffset\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\")\n" +
	"\x0fFileSyncRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"7\n" +
	"\x10FileSyncResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"*\n" +
	"\x10FileCloseRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"8\n" +
	"\x11FileCloseResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"A\n" +
	"\x13FileTruncateRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\";\n" +
	"\x14FileTruncateResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"H\n" +
	"\x0fFileReadRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\rR\tchunkSize\"f\n" +
	"\x10FileReadResponse\x12-\n" +
	"\x05chunk\x18\x01 \x01(\v2\x17.hostserve.v1.FileChunkR\x05chunk\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"Y\n" +
	"\x10FileWriteRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12-\n" +
	"\x05chunk\x18\x02 \x01(\v2\x17.hostserve.v1.FileChunkR\x05chunk\"]\n" +
	"\x11FileWriteResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\rR\fbytesWritten\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"!\n" +
	"\rGetEnvRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"G\n" +
	"\x0eGetEnvResponse\x12\x10\n" +
	"\x03val\x18\x01 \x01(\tR\x03val\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x10\n" +
	"\x0eTempDirRequest\"H\n" +
	"\x0fTempDirResponse\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x15\n" +
	"\x13UserCacheDirRequest\"M\n" +
	"\x14UserCacheDirResponse\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x16\n" +
	"\x14UserConfigDirRequest\"N\n" +
	"\x15UserConfigDirResponse\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x14\n" +
	"\x12UserHomeDirRequest\"L\n" +
	"\x13UserHomeDirResponse\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error*\xcf\x01\n" +
	"\fOpenFileMode\x12\x1e\n" +
	"\x1aOPEN_FILE_MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREAD_ONLY\x10\x01\x12\x12\n" +
	"\x0eWRITE_TRUNCATE\x10\x02\x12\x10\n" +
	"\fWRITE_APPEND\x10\x03\x12\x13\n" +
	"\x0fWRITE_EXCLUSIVE\x10\x04\x12\x0e\n" +
	"\n" +
	"READ_WRITE\x10\x05\x12\x15\n" +
	"\x11READ_WRITE_CREATE\x10\x06\x12\x17\n" +
	"\x13READ_WRITE_TRUNCATE\x10\a\x12\x15\n" +
	"\x11READ_WRITE_APPEND\x10\b2\xfe\r\n" +
	"\vHostService\x12F\n" +
	"\aReadDir\x12\x1c.hostserve.v1.ReadDirRequest\x1a\x1d.hostserve.v1.ReadDirResponse\x12I\n" +
	"\bReadFile\x12\x1d.hostserve.v1.ReadFileRequest\x1a\x1e.hostserve.v1.ReadFileResponse\x12L\n" +
	"\tWriteFile\x12\x1e.hostserve.v1.WriteFileRequest\x1a\x1f.hostserve.v1.WriteFileResponse\x12=\n" +
	"\x04Stat\x12\x19.hostserve.v1.StatRequest\x1a\x1a.hostserve.v1.StatResponse\x12C\n" +
	"\x06Rename\x12\x1b.hostserve.v1.RenameRequest\x1a\x1c.hostserve.v1.RenameResponse\x12@\n" +
	"\x05Mkdir\x12\x1a.hostserve.v1.MkdirRequest\x1a\x1b.hostserve.v1.MkdirResponse\x12I\n" +
	"\bMkdirAll\x12\x1d.hostserve.v1.MkdirAllRequest\x1a\x1e.hostserve.v1.MkdirAllResponse\x12L\n" +
	"\tMkdirTemp\x12\x1e.hostserve.v1.MkdirTempRequest\x1a\x1f.hostserve.v1.MkdirTempResponse\x12O\n" +
	"\n" +
	"FileCreate\x12\x1f.hostserve.v1.FileCreateRequest\x1a .hostserve.v1.FileCreateResponse\x12[\n" +
	"\x0eFileCreateTemp\x12#.hostserve.v1.FileCreateTempRequest\x1a$.hostserve.v1.FileCreateTempResponse\x12I\n" +
	"\bFileOpen\x12\x1d.hostserve.v1.FileOpenRequest\x1a\x1e.hostserve.v1.FileOpenResponse\x12I\n" +
	"\bFileStat\x12\x1d.hostserve.v1.FileStatRequest\x1a\x1e.hostserve.v1.FileStatResponse\x12I\n" +
	"\bFileSeek\x12\x1d.hostserve.v1.FileSeekRequest\x1a\x1e.hostserve.v1.FileSeekResponse\x12I\n" +
	"\bFileSync\x12\x1d.hostserve.v1.FileSyncRequest\x1a\x1e.hostserve.v1.FileSyncResponse\x12L\n" +
	"\tFileClose\x12\x1e.hostserve.v1.FileCloseRequest\x1a\x1f.hostserve.v1.FileCloseResponse\x12U\n" +
	"\fFileTruncate\x12!.hostserve.v1.FileTruncateRequest\x1a\".hostserve.v1.FileTruncateResponse\x12M\n" +
	"\n" +
	"FileReader\x12\x1d.hostserve.v1.FileReadRequest\x1a\x1e.hostserve.v1.FileReadResponse0\x01\x12O\n" +
	"\n" +
	"FileWriter\x12\x1e.hostserve.v1.FileWriteRequest\x1a\x1f.hostserve.v1.FileWriteResponse(\x01\x12C\n" +
	"\x06GetEnv\x12\x1b.hostserve.v1.GetEnvRequest\x1a\x1c.hostserve.v1.GetEnvResponse\x12F\n" +
	"\aTempDir\x12\x1c.hostserve.v1.TempDirRequest\x1a\x1d.hostserve.v1.TempDirResponse\x12U\n" +
	"\fUserCacheDir\x12!.hostserve.v1.UserCacheDirRequest\x1a\".hostserve.v1.UserCacheDirResponse\x12X\n" +
	"\rUserConfigDir\x12\".hostserve.v1.UserConfigDirRequest\x1a#.hostserve.v1.UserConfigDirResponse\x12R\n" +
	"\vUserHomeDir\x12 .hostserve.v1.UserHomeDirRequest\x1a!.hostserve.v1.UserHomeDirResponseB\xc0\x01\n" +
	"\x10com.hostserve.v1B\x0eHostserveProtoP\x01ZKgithub.com/bmj2728/HostServiceTest/shared/protogen/hostserve/v1;hostservev1\xa2\x02\x03HXX\xaa\x02\fHostserve.V1\xca\x02\fHostserve\\V1\xe2\x02\x18Hostserve\\V1\\GPBMetadata\xea\x02\rHostserve::V1b\x06proto3"

var (
	file_hostserve_v1_hostserve_proto_rawDescOnce sync.Once
	file_hostserve_v1_hostserve_proto_rawDescData []byte
)

func file_hostserve_v1_hostserve_proto_rawDescGZIP() []byte {
	file_hostserve_v1_hostserve_proto_rawDescOnce.Do(func() {
		file_hostserve_v1_hostserve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hostserve_v1_hostserve_proto_rawDesc), len(file_hostserve_v1_hostserve_proto_rawDesc)))
	})
	return file_hostserve_v1_hostserve_proto_rawDescData
}

var file_hostserve_v1_hostserve_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hostserve_v1_hostserve_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_hostserve_v1_hostserve_proto_goTypes = []any{
	(OpenFileMode)(0),              // 0: hostserve.v1.OpenFileMode
	(*DirEntry)(nil),               // 1: hostserve.v1.DirEntry
	(*FileChunk)(nil),              // 2: hostserve.v1.FileChunk
	(*FileInfo)(nil),               // 3: hostserve.v1.FileInfo
	(*ReadDirRequest)(nil),         // 4: hostserve.v1.ReadDirRequest
	(*ReadDirResponse)(nil),        // 5: hostserve.v1.ReadDirResponse
	(*ReadFileRequest)(nil),        // 6: hostserve.v1.ReadFileRequest
	(*ReadFileResponse)(nil),       // 7: hostserve.v1.ReadFileResponse
	(*WriteFileRequest)(nil),       // 8: hostserve.v1.WriteFileRequest
	(*WriteFileResponse)(nil),      // 9: hostserve.v1.WriteFileResponse
	(*StatRequest)(nil),            // 10: hostserve.v1.StatRequest
	(*StatResponse)(nil),           // 11: hostserve.v1.StatResponse
	(*RenameRequest)(nil),          // 12: hostserve.v1.RenameRequest
	(*RenameResponse)(nil),         // 13: hostserve.v1.RenameResponse
	(*MkdirRequest)(nil),           // 14: hostserve.v1.MkdirRequest
	(*MkdirResponse)(nil),          // 15: hostserve.v1.MkdirResponse
	(*MkdirAllRequest)(nil),        // 16: hostserve.v1.MkdirAllRequest
	(*MkdirAllResponse)(nil),       // 17: hostserve.v1.MkdirAllResponse
	(*MkdirTempRequest)(nil),       // 18: hostserve.v1.MkdirTempRequest
	(*MkdirTempResponse)(nil),      // 19: hostserve.v1.MkdirTempResponse
	(*FileCreateRequest)(nil),      // 20: hostserve.v1.FileCreateRequest
	(*FileCreateResponse)(nil),     // 21: hostserve.v1.FileCreateResponse
	(*FileCreateTempRequest)(nil),  // 22: hostserve.v1.FileCreateTempRequest
	(*FileCreateTempResponse)(nil), // 23: hostserve.v1.FileCreateTempResponse
	(*FileOpenRequest)(nil),        // 24: hostserve.v1.FileOpenRequest
	(*FileOpenResponse)(nil),       // 25: hostserve.v1.FileOpenResponse
	(*FileStatRequest)(nil),        // 26: hostserve.v1.FileStatRequest
	(*FileStatResponse)(nil),       // 27: hostserve.v1.FileStatResponse
	(*FileSeekRequest)(nil),        // 28: hostserve.v1.FileSeekRequest
	(*FileSeekResponse)(nil),       // 29: hostserve.v1.FileSeekResponse
	(*FileSyncRequest)(nil),        // 30: hostserve.v1.FileSyncRequest
	(*FileSyncResponse)(nil),       // 31: hostserve.v1.FileSyncResponse
	(*FileCloseRequest)(nil),       // 32: hostserve.v1.FileCloseRequest
	(*FileCloseResponse)(nil),      // 33: hostserve.v1.FileCloseResponse
	(*FileTruncateRequest)(nil),    // 34: hostserve.v1.FileTruncateRequest
	(*FileTruncateResponse)(nil),   // 35: hostserve.v1.FileTruncateResponse
	(*FileReadRequest)(nil),        // 36: hostserve.v1.FileReadRequest
	(*FileReadResponse)(nil),       // 37: hostserve.v1.FileReadResponse
	(*FileWriteRequest)(nil),       // 38: hostserve.v1.FileWriteRequest
	(*FileWriteResponse)(nil),      // 39: hostserve.v1.FileWriteResponse
	(*GetEnvRequest)(nil),          // 40: hostserve.v1.GetEnvRequest
	(*GetEnvResponse)(nil),         // 41: hostserve.v1.GetEnvResponse
	(*TempDirRequest)(nil),         // 42: hostserve.v1.TempDirRequest
	(*TempDirResponse)(nil),        // 43: hostserve.v1.TempDirResponse
	(*UserCacheDirRequest)(nil),    // 44: hostserve.v1.UserCacheDirRequest
	(*UserCacheDirResponse)(nil),   // 45: hostserve.v1.UserCacheDirResponse
	(*UserConfigDirRequest)(nil),   // 46: hostserve.v1.UserConfigDirRequest
	(*UserConfigDirResponse)(nil),  // 47: hostserve.v1.UserConfigDirResponse
	(*UserHomeDirRequest)(nil),     // 48: hostserve.v1.UserHomeDirRequest
	(*UserHomeDirResponse)(nil),    // 49: hostserve.v1.UserHomeDirResponse
	(*timestamppb.Timestamp)(nil),  // 50: google.protobuf.Timestamp
}
var file_hostserve_v1_hostserve_proto_depIdxs = []int32{
	50, // 0: hostserve.v1.FileInfo.mod_time:type_name -> google.protobuf.Timestamp
	1,  // 1: hostserve.v1.ReadDirResponse.entries:type_name -> hostserve.v1.DirEntry
	3,  // 2: hostserve.v1.StatResponse.info:type_name -> hostserve.v1.FileInfo
	0,  // 3: hostserve.v1.FileOpenRequest.mode:type_name -> hostserve.v1.OpenFileMode
	3,  // 4: hostserve.v1.FileStatResponse.info:type_name -> hostserve.v1.FileInfo
	2,  // 5: hostserve.v1.FileReadResponse.chunk:type_name -> hostserve.v1.FileChunk
	2,  // 6: hostserve.v1.FileWriteRequest.chunk:type_name -> hostserve.v1.FileChunk
	4,  // 7: hostserve.v1.HostService.ReadDir:input_type -> hostserve.v1.ReadDirRequest
	6,  // 8: hostserve.v1.HostService.ReadFile:input_type -> hostserve.v1.ReadFileRequest
	8,  // 9: hostserve.v1.HostService.WriteFile:input_type -> hostserve.v1.WriteFileRequest
	10, // 10: hostserve.v1.HostService.Stat:input_type -> hostserve.v1.StatRequest
	12, // 11: hostserve.v1.HostService.Rename:input_type -> hostserve.v1.RenameRequest
	14, // 12: hostserve.v1.HostService.Mkdir:input_type -> hostserve.v1.MkdirRequest
	16, // 13: hostserve.v1.HostService.MkdirAll:input_type -> hostserve.v1.MkdirAllRequest
	18, // 14: hostserve.v1.HostService.MkdirTemp:input_type -> hostserve.v1.MkdirTempRequest
	20, // 15: hostserve.v1.HostService.FileCreate:input_type -> hostserve.v1.FileCreateRequest
	22, // 16: hostserve.v1.HostService.FileCreateTemp:input_type -> hostserve.v1.FileCreateTempRequest
	24, // 17: hostserve.v1.HostService.FileOpen:input_type -> hostserve.v1.FileOpenRequest
	26, // 18: hostserve.v1.HostService.FileStat:input_type -> hostserve.v1.FileStatRequest
	28, // 19: hostserve.v1.HostService.FileSeek:input_type -> hostserve.v1.FileSeekRequest
	30, // 20: hostserve.v1.HostService.FileSync:input_type -> hostserve.v1.FileSyncRequest
	32, // 21: hostserve.v1.HostService.FileClose:input_type -> hostserve.v1.FileCloseRequest
	34, // 22: hostserve.v1.HostService.FileTruncate:input_type -> hostserve.v1.FileTruncateRequest
	36, // 23: hostserve.v1.HostService.FileReader:input_type -> hostserve.v1.FileReadRequest
	38, // 24: hostserve.v1.HostService.FileWriter:input_type -> hostserve.v1.FileWriteRequest
	40, // 25: hostserve.v1.HostService.GetEnv:input_type -> hostserve.v1.GetEnvRequest
	42, // 26: hostserve.v1.HostService.TempDir:input_type -> hostserve.v1.TempDirRequest
	44, // 27: hostserve.v1.HostService.UserCacheDir:input_type -> hostserve.v1.UserCacheDirRequest
	46, // 28: hostserve.v1.HostService.UserConfigDir:input_type -> hostserve.v1.UserConfigDirRequest
	48, // 29: hostserve.v1.HostService.UserHomeDir:input_type -> hostserve.v1.UserHomeDirRequest
	5,  // 30: hostserve.v1.HostService.ReadDir:output_type -> hostserve.v1.ReadDirResponse
	7,  // 31: hostserve.v1.HostService.ReadFile:output_type -> hostserve.v1.ReadFileResponse
	9,  // 32: hostserve.v1.HostService.WriteFile:output_type -> hostserve.v1.WriteFileResponse
	11, // 33: hostserve.v1.HostService.Stat:output_type -> hostserve.v1.StatResponse
	13, // 34: hostserve.v1.HostService.Rename:output_type -> hostserve.v1.RenameResponse
	15, // 35: hostserve.v1.HostService.Mkdir:output_type -> hostserve.v1.MkdirResponse
	17, // 36: hostserve.v1.HostService.MkdirAll:output_type -> hostserve.v1.MkdirAllResponse
	19, // 37: hostserve.v1.HostService.MkdirTemp:output_type -> hostserve.v1.MkdirTempResponse
	21, // 38: hostserve.v1.HostService.FileCreate:output_type -> hostserve.v1.FileCreateResponse
	23, // 39: hostserve.v1.HostService.FileCreateTemp:output_type -> hostserve.v1.FileCreateTempResponse
	25, // 40: hostserve.v1.HostService.FileOpen:output_type -> hostserve.v1.FileOpenResponse
	27, // 41: hostserve.v1.HostService.FileStat:output_type -> hostserve.v1.FileStatResponse
	29, // 42: hostserve.v1.HostService.FileSeek:output_type -> hostserve.v1.FileSeekResponse
	31, // 43: hostserve.v1.HostService.FileSync:output_type -> hostserve.v1.FileSyncResponse
	33, // 44: hostserve.v1.HostService.FileClose:output_type -> hostserve.v1.FileCloseResponse
	35, // 45: hostserve.v1.HostService.FileTruncate:output_type -> hostserve.v1.FileTruncateResponse
	37, // 46: hostserve.v1.HostService.FileReader:output_type -> hostserve.v1.FileReadResponse
	39, // 47: hostserve.v1.HostService.FileWriter:output_type -> hostserve.v1.FileWriteResponse
	41, // 48: hostserve.v1.HostService.GetEnv:output_type -> hostserve.v1.GetEnvResponse
	43, // 49: hostserve.v1.HostService.TempDir:output_type -> hostserve.v1.TempDirResponse
	45, // 50: hostserve.v1.HostService.UserCacheDir:output_type -> hostserve.v1.UserCacheDirResponse
	47, // 51: hostserve.v1.HostService.UserConfigDir:output_type -> hostserve.v1.UserConfigDirResponse
	49, // 52: hostserve.v1.HostService.UserHomeDir:output_type -> hostserve.v1.UserHomeDirResponse
	30, // [30:53] is the sub-list for method output_type
	7,  // [7:30] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_hostserve_v1_hostserve_proto_init() }
func file_hostserve_v1_hostserve_proto_init() {
	if File_hostserve_v1_hostserve_proto != nil {
		return
	}
	file_hostserve_v1_hostserve_proto_msgTypes[4].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[6].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[8].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[10].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[14].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[16].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[18].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[20].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[22].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[24].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[26].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[28].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[30].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[32].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[34].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[36].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[38].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[40].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[42].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[44].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[46].OneofWrappers = []any{}
	file_hostserve_v1_hostserve_proto_msgTypes[48].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hostserve_v1_hostserve_proto_rawDesc), len(file_hostserve_v1_hostserve_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostserve_v1_hostserve_proto_goTypes,
		DependencyIndexes: file_hostserve_v1_hostserve_proto_depIdxs,
		EnumInfos:         file_hostserve_v1_hostserve_proto_enumTypes,
		MessageInfos:      file_hostserve_v1_hostserve_proto_msgTypes,
	}.Build()
	File_hostserve_v1_hostserve_proto = out.File
	file_hostserve_v1_hostserve_proto_goTypes = nil
	file_hostserve_v1_hostserve_proto_depIdxs = nil
}
