// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: hostdemo/v1/hostdemo.proto

package hostdemov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostService   uint32                 `protobuf:"varint,1,opt,name=host_service,json=hostService,proto3" json:"host_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostServiceRequest) Reset() {
	*x = HostServiceRequest{}
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostServiceRequest) ProtoMessage() {}

func (x *HostServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostServiceRequest.ProtoReflect.Descriptor instead.
func (*HostServiceRequest) Descriptor() ([]byte, []int) {
	return file_hostdemo_v1_hostdemo_proto_rawDescGZIP(), []int{0}
}

func (x *HostServiceRequest) GetHostService() uint32 {
	if x != nil {
		return x.HostService
	}
	return 0
}

type HostServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostServiceResponse) Reset() {
	*x = HostServiceResponse{}
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostServiceResponse) ProtoMessage() {}

func (x *HostServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostServiceResponse.ProtoReflect.Descriptor instead.
func (*HostServiceResponse) Descriptor() ([]byte, []int) {
	return file_hostdemo_v1_hostdemo_proto_rawDescGZIP(), []int{1}
}

func (x *HostServiceResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HostServiceResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetEnvDemoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvDemoReq) Reset() {
	*x = GetEnvDemoReq{}
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvDemoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvDemoReq) ProtoMessage() {}

func (x *GetEnvDemoReq) ProtoReflect() protoreflect.Message {
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvDemoReq.ProtoReflect.Descriptor instead.
func (*GetEnvDemoReq) Descriptor() ([]byte, []int) {
	return file_hostdemo_v1_hostdemo_proto_rawDescGZIP(), []int{2}
}

func (x *GetEnvDemoReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetEnvDemoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          string                 `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvDemoResp) Reset() {
	*x = GetEnvDemoResp{}
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvDemoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvDemoResp) ProtoMessage() {}

func (x *GetEnvDemoResp) ProtoReflect() protoreflect.Message {
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvDemoResp.ProtoReflect.Descriptor instead.
func (*GetEnvDemoResp) Descriptor() ([]byte, []int) {
	return file_hostdemo_v1_hostdemo_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnvDemoResp) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

func (x *GetEnvDemoResp) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type EnvDemoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvDemoReq) Reset() {
	*x = EnvDemoReq{}
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvDemoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvDemoReq) ProtoMessage() {}

func (x *EnvDemoReq) ProtoReflect() protoreflect.Message {
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvDemoReq.ProtoReflect.Descriptor instead.
func (*EnvDemoReq) Descriptor() ([]byte, []int) {
	return file_hostdemo_v1_hostdemo_proto_rawDescGZIP(), []int{4}
}

type EnvDemoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          string                 `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvDemoResp) Reset() {
	*x = EnvDemoResp{}
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvDemoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvDemoResp) ProtoMessage() {}

func (x *EnvDemoResp) ProtoReflect() protoreflect.Message {
	mi := &file_hostdemo_v1_hostdemo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvDemoResp.ProtoReflect.Descriptor instead.
func (*EnvDemoResp) Descriptor() ([]byte, []int) {
	return file_hostdemo_v1_hostdemo_proto_rawDescGZIP(), []int{5}
}

func (x *EnvDemoResp) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

func (x *EnvDemoResp) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_hostdemo_v1_hostdemo_proto protoreflect.FileDescriptor

const file_hostdemo_v1_hostdemo_proto_rawDesc = "" +
	"\n" +
	"\x1ahostdemo/v1/hostdemo.proto\x12\vhostdemo.v1\"7\n" +
	"\x12HostServiceRequest\x12!\n" +
	"\fhost_service\x18\x01 \x01(\rR\vhostService\"W\n" +
	"\x13HostServiceResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"!\n" +
	"\rGetEnvDemoReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"I\n" +
	"\x0eGetEnvDemoResp\x12\x12\n" +
	"\x04resp\x18\x01 \x01(\tR\x04resp\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\f\n" +
	"\n" +
	"EnvDemoReq\"F\n" +
	"\vEnvDemoResp\x12\x12\n" +
	"\x04resp\x18\x01 \x01(\tR\x04resp\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xeb\x01\n" +
	"\bHostDemo\x12Z\n" +
	"\x15EstablishHostServices\x12\x1f.hostdemo.v1.HostServiceRequest\x1a .hostdemo.v1.HostServiceResponse\x12E\n" +
	"\n" +
	"GetEnvDemo\x12\x1a.hostdemo.v1.GetEnvDemoReq\x1a\x1b.hostdemo.v1.GetEnvDemoResp\x12<\n" +
	"\aEnvDemo\x12\x17.hostdemo.v1.EnvDemoReq\x1a\x18.hostdemo.v1.EnvDemoRespB\xb8\x01\n" +
	"\x0fcom.hostdemo.v1B\rHostdemoProtoP\x01ZIgithub.com/bmj2728/HostServiceTest/shared/protogen/hostdemo/v1;hostdemov1\xa2\x02\x03HXX\xaa\x02\vHostdemo.V1\xca\x02\vHostdemo\\V1\xe2\x02\x17Hostdemo\\V1\\GPBMetadata\xea\x02\fHostdemo::V1b\x06proto3"

var (
	file_hostdemo_v1_hostdemo_proto_rawDescOnce sync.Once
	file_hostdemo_v1_hostdemo_proto_rawDescData []byte
)

func file_hostdemo_v1_hostdemo_proto_rawDescGZIP() []byte {
	file_hostdemo_v1_hostdemo_proto_rawDescOnce.Do(func() {
		file_hostdemo_v1_hostdemo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hostdemo_v1_hostdemo_proto_rawDesc), len(file_hostdemo_v1_hostdemo_proto_rawDesc)))
	})
	return file_hostdemo_v1_hostdemo_proto_rawDescData
}

var file_hostdemo_v1_hostdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hostdemo_v1_hostdemo_proto_goTypes = []any{
	(*HostServiceRequest)(nil),  // 0: hostdemo.v1.HostServiceRequest
	(*HostServiceResponse)(nil), // 1: hostdemo.v1.HostServiceResponse
	(*GetEnvDemoReq)(nil),       // 2: hostdemo.v1.GetEnvDemoReq
	(*GetEnvDemoResp)(nil),      // 3: hostdemo.v1.GetEnvDemoResp
	(*EnvDemoReq)(nil),          // 4: hostdemo.v1.EnvDemoReq
	(*EnvDemoResp)(nil),         // 5: hostdemo.v1.EnvDemoResp
}
var file_hostdemo_v1_hostdemo_proto_depIdxs = []int32{
	0, // 0: hostdemo.v1.HostDemo.EstablishHostServices:input_type -> hostdemo.v1.HostServiceRequest
	2, // 1: hostdemo.v1.HostDemo.GetEnvDemo:input_type -> hostdemo.v1.GetEnvDemoReq
	4, // 2: hostdemo.v1.HostDemo.EnvDemo:input_type -> hostdemo.v1.EnvDemoReq
	1, // 3: hostdemo.v1.HostDemo.EstablishHostServices:output_type -> hostdemo.v1.HostServiceResponse
	3, // 4: hostdemo.v1.HostDemo.GetEnvDemo:output_type -> hostdemo.v1.GetEnvDemoResp
	5, // 5: hostdemo.v1.HostDemo.EnvDemo:output_type -> hostdemo.v1.EnvDemoResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hostdemo_v1_hostdemo_proto_init() }
func file_hostdemo_v1_hostdemo_proto_init() {
	if File_hostdemo_v1_hostdemo_proto != nil {
		return
	}
	file_hostdemo_v1_hostdemo_proto_msgTypes[1].OneofWrappers = []any{}
	file_hostdemo_v1_hostdemo_proto_msgTypes[3].OneofWrappers = []any{}
	file_hostdemo_v1_hostdemo_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hostdemo_v1_hostdemo_proto_rawDesc), len(file_hostdemo_v1_hostdemo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostdemo_v1_hostdemo_proto_goTypes,
		DependencyIndexes: file_hostdemo_v1_hostdemo_proto_depIdxs,
		MessageInfos:      file_hostdemo_v1_hostdemo_proto_msgTypes,
	}.Build()
	File_hostdemo_v1_hostdemo_proto = out.File
	file_hostdemo_v1_hostdemo_proto_goTypes = nil
	file_hostdemo_v1_hostdemo_proto_depIdxs = nil
}
