// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: hostdemo/v1/hostdemo.proto

package hostdemov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostDemo_EstablishHostServices_FullMethodName = "/hostdemo.v1.HostDemo/EstablishHostServices"
	HostDemo_GetEnvDemo_FullMethodName            = "/hostdemo.v1.HostDemo/GetEnvDemo"
	HostDemo_EnvDemo_FullMethodName               = "/hostdemo.v1.HostDemo/EnvDemo"
)

// HostDemoClient is the client API for HostDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostDemoClient interface {
	EstablishHostServices(ctx context.Context, in *HostServiceRequest, opts ...grpc.CallOption) (*HostServiceResponse, error)
	GetEnvDemo(ctx context.Context, in *GetEnvDemoReq, opts ...grpc.CallOption) (*GetEnvDemoResp, error)
	EnvDemo(ctx context.Context, in *EnvDemoReq, opts ...grpc.CallOption) (*EnvDemoResp, error)
}

type hostDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewHostDemoClient(cc grpc.ClientConnInterface) HostDemoClient {
	return &hostDemoClient{cc}
}

func (c *hostDemoClient) EstablishHostServices(ctx context.Context, in *HostServiceRequest, opts ...grpc.CallOption) (*HostServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostServiceResponse)
	err := c.cc.Invoke(ctx, HostDemo_EstablishHostServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostDemoClient) GetEnvDemo(ctx context.Context, in *GetEnvDemoReq, opts ...grpc.CallOption) (*GetEnvDemoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnvDemoResp)
	err := c.cc.Invoke(ctx, HostDemo_GetEnvDemo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostDemoClient) EnvDemo(ctx context.Context, in *EnvDemoReq, opts ...grpc.CallOption) (*EnvDemoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvDemoResp)
	err := c.cc.Invoke(ctx, HostDemo_EnvDemo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostDemoServer is the server API for HostDemo service.
// All implementations must embed UnimplementedHostDemoServer
// for forward compatibility.
type HostDemoServer interface {
	EstablishHostServices(context.Context, *HostServiceRequest) (*HostServiceResponse, error)
	GetEnvDemo(context.Context, *GetEnvDemoReq) (*GetEnvDemoResp, error)
	EnvDemo(context.Context, *EnvDemoReq) (*EnvDemoResp, error)
	mustEmbedUnimplementedHostDemoServer()
}

// UnimplementedHostDemoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostDemoServer struct{}

func (UnimplementedHostDemoServer) EstablishHostServices(context.Context, *HostServiceRequest) (*HostServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstablishHostServices not implemented")
}
func (UnimplementedHostDemoServer) GetEnvDemo(context.Context, *GetEnvDemoReq) (*GetEnvDemoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnvDemo not implemented")
}
func (UnimplementedHostDemoServer) EnvDemo(context.Context, *EnvDemoReq) (*EnvDemoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnvDemo not implemented")
}
func (UnimplementedHostDemoServer) mustEmbedUnimplementedHostDemoServer() {}
func (UnimplementedHostDemoServer) testEmbeddedByValue()                  {}

// UnsafeHostDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostDemoServer will
// result in compilation errors.
type UnsafeHostDemoServer interface {
	mustEmbedUnimplementedHostDemoServer()
}

func RegisterHostDemoServer(s grpc.ServiceRegistrar, srv HostDemoServer) {
	// If the following call pancis, it indicates UnimplementedHostDemoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostDemo_ServiceDesc, srv)
}

func _HostDemo_EstablishHostServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostDemoServer).EstablishHostServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostDemo_EstablishHostServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostDemoServer).EstablishHostServices(ctx, req.(*HostServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostDemo_GetEnvDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvDemoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostDemoServer).GetEnvDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostDemo_GetEnvDemo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostDemoServer).GetEnvDemo(ctx, req.(*GetEnvDemoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostDemo_EnvDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvDemoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostDemoServer).EnvDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostDemo_EnvDemo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostDemoServer).EnvDemo(ctx, req.(*EnvDemoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HostDemo_ServiceDesc is the grpc.ServiceDesc for HostDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hostdemo.v1.HostDemo",
	HandlerType: (*HostDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstablishHostServices",
			Handler:    _HostDemo_EstablishHostServices_Handler,
		},
		{
			MethodName: "GetEnvDemo",
			Handler:    _HostDemo_GetEnvDemo_Handler,
		},
		{
			MethodName: "EnvDemo",
			Handler:    _HostDemo_EnvDemo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hostdemo/v1/hostdemo.proto",
}
