syntax = "proto3";
package hostserve.v1;
option go_package = "github.com/bmj2728/HostServiceTest/shared/protogen/hostserve/v1;hostservev1";

import "google/protobuf/timestamp.proto";

//////////////////////////////////////ENUMs////////////////////////////////////////////////////////////////////////////

enum OpenFileFlags {
  OPEN_FILE_MODE_UNSPECIFIED = 0;

  // Read modes
  READ_ONLY = 1;                    // O_RDONLY

  // Write modes
  WRITE_TRUNCATE = 2;               // O_WRONLY|O_CREATE|O_TRUNC (like os.Create)
  WRITE_APPEND = 3;                 // O_WRONLY|O_CREATE|O_APPEND
  WRITE_EXCLUSIVE = 4;              // O_WRONLY|O_CREATE|O_EXCL (fail if exists)

  // Read/Write modes
  READ_WRITE = 5;                   // O_RDWR
  READ_WRITE_CREATE = 6;            // O_RDWR|O_CREATE
  READ_WRITE_TRUNCATE = 7;          // O_RDWR|O_CREATE|O_TRUNC
  READ_WRITE_APPEND = 8;            // O_RDWR|O_CREATE|O_APPEND
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////Service Endpoints//////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// HostService is a service provided by the host process and is generally preferred over granting direct
// access to the plugin process
service HostService {

  // TODO Implement ReadFileAt/FileReaderAt & WriteFileAt/FileWriterAt

  // FS Endpoints - Unary Calls
  rpc ReadDir(ReadDirRequest) returns (ReadDirResponse);
  rpc ReadFile(ReadFileRequest) returns (ReadFileResponse);
  rpc ReadFileAt(ReadFileAtRequest) returns (ReadFileAtResponse); // unary read of pre-determined size from offset
  rpc WriteFile(WriteFileRequest) returns (WriteFileResponse);
  rpc WriteFileAt(WriteFileAtRequest) returns (WriteFileAtResponse); // unary write at offset
  rpc Stat(StatRequest) returns (StatResponse); // convenience for open->stat->close
  rpc Rename(RenameRequest) returns (RenameResponse);
  rpc Remove(RemoveRequest) returns (RemoveResponse);
  rpc RemoveAll(RemoveAllRequest) returns (RemoveAllResponse);
  rpc Mkdir(MkdirRequest) returns (MkdirResponse);
  rpc MkdirAll(MkdirAllRequest) returns (MkdirAllResponse);
  rpc MkdirTemp(MkdirTempRequest) returns (MkdirTempResponse);
  rpc Chmod(ChmodRequest) returns (ChmodResponse);
  rpc Chown(ChownRequest) returns (ChownResponse);
  rpc Chtimes(ChtimesRequest) returns (ChtimesResponse);
  rpc Lchown(LchownRequest) returns (LchownResponse);
  rpc Lstat(LstatRequest) returns (LstatResponse);
  rpc Readlink(ReadlinkRequest) returns (ReadlinkResponse);
  rpc Link(LinkRequest) returns (LinkResponse);
  rpc Symlink(SymlinkRequest) returns (SymlinkResponse);

  // FS - File Handle Endpoints
  rpc FileCreate(FileCreateRequest) returns (FileCreateResponse);
  rpc FileCreateTemp(FileCreateTempRequest) returns (FileCreateTempResponse);
  rpc FileOpen(FileOpenRequest) returns (FileOpenResponse);
  rpc FileStat(FileStatRequest) returns (FileStatResponse);
  rpc FileSeek(FileSeekRequest) returns (FileSeekResponse);
  rpc FileSync(FileSyncRequest) returns (FileSyncResponse);
  rpc FileClose(FileCloseRequest) returns (FileCloseResponse);
  rpc FileTruncate(FileTruncateRequest) returns (FileTruncateResponse);
  rpc FileChmod(FileChmodRequest) returns (FileChmodResponse);
  rpc FileChown(FileChownRequest) returns (FileChownResponse);

  // FS - Streaming File Ops -
  rpc FileReader(FileReadRequest) returns (stream FileReadResponse);
  rpc FileReaderAt(FileReadAtRequest) returns (stream FileReadAtResponse);
  rpc FileWriter(stream FileWriteRequest) returns (FileWriteResponse);
  rpc FileWriterAt(stream FileWriteAtRequest) returns (FileWriteAtResponse);

  // Env Endpoints
  rpc Getuid(GetuidRequest) returns (GetuidResponse);
  rpc Getgid(GetgidRequest) returns (GetgidResponse);
  rpc Geteuid(GeteuidRequest) returns (GeteuidResponse);
  rpc Getegid(GetegidRequest) returns (GetegidResponse);
  rpc GetGroups(GetGroupsRequest) returns (GetGroupsResponse);
  rpc Getpid(GetpidRequest) returns (GetpidResponse);
  rpc Getppid(GetppidRequest) returns (GetppidResponse);
  rpc GetEnv(GetEnvRequest) returns (GetEnvResponse);
  rpc TempDir(TempDirRequest) returns (TempDirResponse);
  rpc UserCacheDir(UserCacheDirRequest) returns (UserCacheDirResponse);
  rpc UserConfigDir(UserConfigDirRequest) returns (UserConfigDirResponse);
  rpc UserHomeDir(UserHomeDirRequest) returns (UserHomeDirResponse);
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////Type Definitions///////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// DirEntry represents the basic dir entry data
message DirEntry {
  string name = 1;
  bool is_dir = 2;
}

message FileChunk {
  bytes data = 1;
  uint64 offset = 2;
  bool is_final = 3;
}

message FileInfo {
  string name = 1;
  int64 size = 2;
  uint32 mode = 3;
  google.protobuf.Timestamp mod_time = 4;
  bool is_dir =5;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////FS Messages/////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

message ReadDirRequest {
  string root_dir =1;
  string path = 2;
}

message ReadDirResponse {
  repeated DirEntry entries = 1;
  optional string error = 2;
}

message ReadFileRequest {
  string root_dir = 1;
  string path = 2;
}

message ReadFileResponse {
  bytes contents = 1;
  optional string error = 2;
}

message ReadFileAtRequest {
  string root_dir = 1;
  string path = 2;
  uint64 offset = 3;
  uint32 read_size = 4;
}

message ReadFileAtResponse {
  bytes contents = 1;
  optional string error = 2;
}

message WriteFileRequest {
  string root_dir = 1;
  string path = 2;
  bytes data = 3;
  uint32 perm = 4;
}

message WriteFileResponse {
  optional string error = 1;
}

message WriteFileAtRequest {
  string root_dir = 1;
  string path = 2;
  uint32 offset = 3;
  bytes data = 4;
  uint32 perm = 5;
}

message WriteFileAtResponse {
  optional string error = 1;
}

message StatRequest {
  string root_dir = 1;
  string path = 2;
}

message StatResponse {
  FileInfo info = 1;
  optional string error =2;
}

message  RenameRequest {
  string root_dir = 1;
  string old_name = 2;
  string new_name =3;
}

message RenameResponse {
  optional string error = 1;
}

message RemoveRequest {
  string root_dir = 1;
  string path = 2;
}

message RemoveResponse {
  optional string error = 1;
}

message RemoveAllRequest {
  string root_dir = 1;
  string path = 2;
}

message RemoveAllResponse {
  optional string error = 1;
}

message MkdirRequest {
  string root_dir = 1;
  string name = 2;
  uint32 perm = 3;
}

message MkdirResponse {
  optional string error = 1;
}

message MkdirAllRequest {
  string root_dir = 1;
  string path = 2;
  uint32 perm = 3;
}

message MkdirAllResponse {
  optional string error = 1;
}

message MkdirTempRequest {
  string root_dir = 1;
  string pattern = 2;
}

message MkdirTempResponse {
  string path = 1;
  optional string error = 2;
}

message ChmodRequest {
  string root_dir = 1;
  string path = 2;
  uint32 mode =3;
}

message ChmodResponse {
  optional string error = 1;
}

message ChownRequest {
  string root_dir = 1;
  string path = 2;
  int32 uid = 3;
  int32 gid = 4;
}

message ChownResponse {
  optional string error = 1;
}

message ChtimesRequest {
  string root_dir = 1;
  string path = 2;
  google.protobuf.Timestamp atime = 3;
  google.protobuf.Timestamp mtime = 4;

}

message ChtimesResponse {
  optional string error = 1;
}

message LchownRequest {
  string root_dir = 1;
  string path = 2;
  int32 uid = 3;
  int32 gid = 4;
}

message LchownResponse {
  optional string error = 1;
}

message LstatRequest {
  string root_dir = 1;
  string path = 2;
}

message LstatResponse {
  FileInfo info = 1;
  optional string error = 2;
}

message ReadlinkRequest {
  string root_dir = 1;
  string path = 2;
}

message ReadlinkResponse {
  string destination = 1;
  optional string error = 2;
}

message LinkRequest {
  string root_dir = 1;
  string old_path = 2;
  string new_path = 3;
}

message LinkResponse {
  optional string error = 1;
}

message SymlinkRequest {
  string root_dir = 1;
  string old_path = 2;
  string new_path = 3;
}

message SymlinkResponse {
  optional string error = 1;
}

// Handle Related

message FileCreateRequest {
  string root_dir =1;
  string path = 2;
}

message FileCreateResponse {
  string handle = 1;
  optional string error = 3;
}

message FileCreateTempRequest {
  string root_dir = 1;
  string pattern = 2;
}

message FileCreateTempResponse {
  string handle = 1;
  optional string error = 3;
}

message FileOpenRequest {
  string root_dir = 1;
  string path = 2;
  OpenFileFlags flags = 3;
  uint32 perm = 4;
}

message FileOpenResponse {
  string handle = 1;
  uint64 size = 2;
  optional string error = 3;
}

message FileStatRequest {
  string handle = 1;
}

message FileStatResponse {
  FileInfo info = 1;
  optional string error =2;
}

message FileSeekRequest {
  string handle = 1;
  uint64 offset = 2;
  uint32 whence = 3;
}

message FileSeekResponse {
  uint64 new_offset = 1;
  optional string error = 2;
}

message FileSyncRequest {
  string handle = 1;
}

message FileSyncResponse {
  optional string error = 1;
}

message FileCloseRequest {
  string handle = 1;
}

message FileCloseResponse {
  optional string error = 1;
}

message FileTruncateRequest {
  string handle = 1;
  int64 size = 2;
}

message FileTruncateResponse {
  optional string error = 1;
}

message FileChmodRequest {
  string handle = 1;
  uint32 mode = 2;
}

message FileChmodResponse {
  optional string error = 1;
}

message FileChownRequest {
  string handle = 1;
  int32 uid = 2;
  int32 gid = 3;
}

message FileChownResponse {
  optional string error = 1;
}

// STREAMING OPS

message FileReadRequest {
  string handle = 1;
  uint32 chunk_size = 2;
}

message FileReadResponse {
  FileChunk chunk = 1;
  optional string error = 2;
}

message FileReadAtRequest {
  string handle = 1;
  uint64 offset = 2;
  uint32 chunk_size = 3;
}

message FileReadAtResponse {
  FileChunk chunk = 1;
  optional string error = 2;
}

message FileWriteRequest {
  string handle = 1;
  FileChunk chunk = 2;
}

message FileWriteResponse {
  uint32 bytes_written = 1;
  optional string error = 2;
}

message FileWriteAtRequest {
  string handle = 1;
  uint64 offset = 2;
  FileChunk chunk = 3;
}

message FileWriteAtResponse {
  uint32 bytes_written = 1;
  optional string error = 2;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////Env Service Messages////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

message GetuidRequest {

}

message GetuidResponse {
  int32 uid = 1;
  optional string error =2;
}

message GetgidRequest {

}

message GetgidResponse {
  int32 gid = 1;
  optional string error =2;
}

message GeteuidRequest {

}

message GeteuidResponse {
  int32 euid = 1;
  optional string error =2;
}

message GetegidRequest {

}

message GetegidResponse {
  int32 egid = 1;
  optional string error =2;
}

message GetGroupsRequest {

}

message GetGroupsResponse {
  repeated int32 groups = 1;
  optional string error = 2;
}

message GetpidRequest {

}

message GetpidResponse {
  int32 pid = 1;
  optional string error =2;
}

message GetppidRequest {

}

message GetppidResponse {
  int32 ppid = 1;
  optional string error =2;
}

message GetEnvRequest {
  string key = 1;
}

message GetEnvResponse {
  string val = 1;
  optional string error = 2;
}

message TempDirRequest {

}

message TempDirResponse {
  string dir = 1;
  optional string error = 2;
}

message UserCacheDirRequest {

}

message UserCacheDirResponse {
  string dir = 1;
  optional string error = 2;
}

message UserConfigDirRequest {

}

message UserConfigDirResponse {
  string dir = 1;
  optional string error = 2;
}

message UserHomeDirRequest {

}

message UserHomeDirResponse {
  string dir = 1;
  optional string error = 2;
}