# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hostserve.v1 import hostserve_pb2 as hostserve_dot_v1_dot_hostserve__pb2


class HostServiceStub(object):
    """/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////Service Endpoints//////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    HostService is a service provided by the host process and is generally preferred over granting direct
    access to the plugin process
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadDir = channel.unary_unary(
                '/hostserve.v1.HostService/ReadDir',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.ReadDirRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ReadDirResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/hostserve.v1.HostService/ReadFile',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/hostserve.v1.HostService/WriteFile',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/hostserve.v1.HostService/Stat',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.StatRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.StatResponse.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/hostserve.v1.HostService/Rename',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.RenameRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.RenameResponse.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/hostserve.v1.HostService/Remove',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.RemoveRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.RemoveResponse.FromString,
                _registered_method=True)
        self.RemoveAll = channel.unary_unary(
                '/hostserve.v1.HostService/RemoveAll',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.RemoveAllRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.RemoveAllResponse.FromString,
                _registered_method=True)
        self.Mkdir = channel.unary_unary(
                '/hostserve.v1.HostService/Mkdir',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirResponse.FromString,
                _registered_method=True)
        self.MkdirAll = channel.unary_unary(
                '/hostserve.v1.HostService/MkdirAll',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirAllRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirAllResponse.FromString,
                _registered_method=True)
        self.MkdirTemp = channel.unary_unary(
                '/hostserve.v1.HostService/MkdirTemp',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirTempRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirTempResponse.FromString,
                _registered_method=True)
        self.Chmod = channel.unary_unary(
                '/hostserve.v1.HostService/Chmod',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.ChmodRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ChmodResponse.FromString,
                _registered_method=True)
        self.Chown = channel.unary_unary(
                '/hostserve.v1.HostService/Chown',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.ChownRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ChownResponse.FromString,
                _registered_method=True)
        self.Chtimes = channel.unary_unary(
                '/hostserve.v1.HostService/Chtimes',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.ChtimesRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ChtimesResponse.FromString,
                _registered_method=True)
        self.Lchown = channel.unary_unary(
                '/hostserve.v1.HostService/Lchown',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.LchownRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.LchownResponse.FromString,
                _registered_method=True)
        self.Lstat = channel.unary_unary(
                '/hostserve.v1.HostService/Lstat',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.LstatRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.LstatResponse.FromString,
                _registered_method=True)
        self.Readlink = channel.unary_unary(
                '/hostserve.v1.HostService/Readlink',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.ReadlinkRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ReadlinkResponse.FromString,
                _registered_method=True)
        self.Link = channel.unary_unary(
                '/hostserve.v1.HostService/Link',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.LinkRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.LinkResponse.FromString,
                _registered_method=True)
        self.Symlink = channel.unary_unary(
                '/hostserve.v1.HostService/Symlink',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.SymlinkRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.SymlinkResponse.FromString,
                _registered_method=True)
        self.FileCreate = channel.unary_unary(
                '/hostserve.v1.HostService/FileCreate',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileCreateRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileCreateResponse.FromString,
                _registered_method=True)
        self.FileCreateTemp = channel.unary_unary(
                '/hostserve.v1.HostService/FileCreateTemp',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileCreateTempRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileCreateTempResponse.FromString,
                _registered_method=True)
        self.FileOpen = channel.unary_unary(
                '/hostserve.v1.HostService/FileOpen',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileOpenRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileOpenResponse.FromString,
                _registered_method=True)
        self.FileStat = channel.unary_unary(
                '/hostserve.v1.HostService/FileStat',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileStatRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileStatResponse.FromString,
                _registered_method=True)
        self.FileSeek = channel.unary_unary(
                '/hostserve.v1.HostService/FileSeek',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileSeekRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileSeekResponse.FromString,
                _registered_method=True)
        self.FileSync = channel.unary_unary(
                '/hostserve.v1.HostService/FileSync',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileSyncRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileSyncResponse.FromString,
                _registered_method=True)
        self.FileClose = channel.unary_unary(
                '/hostserve.v1.HostService/FileClose',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileCloseRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileCloseResponse.FromString,
                _registered_method=True)
        self.FileTruncate = channel.unary_unary(
                '/hostserve.v1.HostService/FileTruncate',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileTruncateRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileTruncateResponse.FromString,
                _registered_method=True)
        self.FileChmod = channel.unary_unary(
                '/hostserve.v1.HostService/FileChmod',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileChmodRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileChmodResponse.FromString,
                _registered_method=True)
        self.FileChown = channel.unary_unary(
                '/hostserve.v1.HostService/FileChown',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileChownRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileChownResponse.FromString,
                _registered_method=True)
        self.FileReadSection = channel.unary_unary(
                '/hostserve.v1.HostService/FileReadSection',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadSectionRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadSectionResponse.FromString,
                _registered_method=True)
        self.FileWriteSection = channel.unary_unary(
                '/hostserve.v1.HostService/FileWriteSection',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteSectionRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteSectionResponse.FromString,
                _registered_method=True)
        self.FileReader = channel.unary_stream(
                '/hostserve.v1.HostService/FileReader',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadResponse.FromString,
                _registered_method=True)
        self.FileReaderAt = channel.unary_stream(
                '/hostserve.v1.HostService/FileReaderAt',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadAtRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadAtResponse.FromString,
                _registered_method=True)
        self.FileWriter = channel.stream_unary(
                '/hostserve.v1.HostService/FileWriter',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteResponse.FromString,
                _registered_method=True)
        self.FileWriterAt = channel.stream_unary(
                '/hostserve.v1.HostService/FileWriterAt',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteAtRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteAtResponse.FromString,
                _registered_method=True)
        self.Getuid = channel.unary_unary(
                '/hostserve.v1.HostService/Getuid',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetuidRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetuidResponse.FromString,
                _registered_method=True)
        self.Getgid = channel.unary_unary(
                '/hostserve.v1.HostService/Getgid',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetgidRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetgidResponse.FromString,
                _registered_method=True)
        self.Geteuid = channel.unary_unary(
                '/hostserve.v1.HostService/Geteuid',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.GeteuidRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GeteuidResponse.FromString,
                _registered_method=True)
        self.Getegid = channel.unary_unary(
                '/hostserve.v1.HostService/Getegid',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetegidRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetegidResponse.FromString,
                _registered_method=True)
        self.GetGroups = channel.unary_unary(
                '/hostserve.v1.HostService/GetGroups',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetGroupsRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetGroupsResponse.FromString,
                _registered_method=True)
        self.Getpid = channel.unary_unary(
                '/hostserve.v1.HostService/Getpid',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetpidRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetpidResponse.FromString,
                _registered_method=True)
        self.Getppid = channel.unary_unary(
                '/hostserve.v1.HostService/Getppid',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetppidRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetppidResponse.FromString,
                _registered_method=True)
        self.GetEnv = channel.unary_unary(
                '/hostserve.v1.HostService/GetEnv',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetEnvRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetEnvResponse.FromString,
                _registered_method=True)
        self.TempDir = channel.unary_unary(
                '/hostserve.v1.HostService/TempDir',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.TempDirRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.TempDirResponse.FromString,
                _registered_method=True)
        self.UserCacheDir = channel.unary_unary(
                '/hostserve.v1.HostService/UserCacheDir',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.UserCacheDirRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.UserCacheDirResponse.FromString,
                _registered_method=True)
        self.UserConfigDir = channel.unary_unary(
                '/hostserve.v1.HostService/UserConfigDir',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.UserConfigDirRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.UserConfigDirResponse.FromString,
                _registered_method=True)
        self.UserHomeDir = channel.unary_unary(
                '/hostserve.v1.HostService/UserHomeDir',
                request_serializer=hostserve_dot_v1_dot_hostserve__pb2.UserHomeDirRequest.SerializeToString,
                response_deserializer=hostserve_dot_v1_dot_hostserve__pb2.UserHomeDirResponse.FromString,
                _registered_method=True)


class HostServiceServicer(object):
    """/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////Service Endpoints//////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    HostService is a service provided by the host process and is generally preferred over granting direct
    access to the plugin process
    """

    def ReadDir(self, request, context):
        """FS Endpoints - Unary Calls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """convenience for open->stat->close
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MkdirAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MkdirTemp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chmod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chtimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lchown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lstat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Readlink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Link(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Symlink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileCreate(self, request, context):
        """FS - File Handle Endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileCreateTemp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileOpen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileSeek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileClose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileTruncate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileChmod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileChown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileReadSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileWriteSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileReader(self, request, context):
        """FS - Streaming File Ops -
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileReaderAt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileWriter(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileWriterAt(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Getuid(self, request, context):
        """Env Endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Getgid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Geteuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Getegid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Getpid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Getppid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TempDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserCacheDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserConfigDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserHomeDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadDir': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDir,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ReadDirRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.ReadDirResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ReadFileRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.WriteFileRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.WriteFileResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.StatRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.StatResponse.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.RenameRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.RenameResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.RemoveRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.RemoveResponse.SerializeToString,
            ),
            'RemoveAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAll,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.RemoveAllRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.RemoveAllResponse.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirResponse.SerializeToString,
            ),
            'MkdirAll': grpc.unary_unary_rpc_method_handler(
                    servicer.MkdirAll,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirAllRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirAllResponse.SerializeToString,
            ),
            'MkdirTemp': grpc.unary_unary_rpc_method_handler(
                    servicer.MkdirTemp,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirTempRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.MkdirTempResponse.SerializeToString,
            ),
            'Chmod': grpc.unary_unary_rpc_method_handler(
                    servicer.Chmod,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ChmodRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.ChmodResponse.SerializeToString,
            ),
            'Chown': grpc.unary_unary_rpc_method_handler(
                    servicer.Chown,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ChownRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.ChownResponse.SerializeToString,
            ),
            'Chtimes': grpc.unary_unary_rpc_method_handler(
                    servicer.Chtimes,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ChtimesRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.ChtimesResponse.SerializeToString,
            ),
            'Lchown': grpc.unary_unary_rpc_method_handler(
                    servicer.Lchown,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.LchownRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.LchownResponse.SerializeToString,
            ),
            'Lstat': grpc.unary_unary_rpc_method_handler(
                    servicer.Lstat,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.LstatRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.LstatResponse.SerializeToString,
            ),
            'Readlink': grpc.unary_unary_rpc_method_handler(
                    servicer.Readlink,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.ReadlinkRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.ReadlinkResponse.SerializeToString,
            ),
            'Link': grpc.unary_unary_rpc_method_handler(
                    servicer.Link,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.LinkRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.LinkResponse.SerializeToString,
            ),
            'Symlink': grpc.unary_unary_rpc_method_handler(
                    servicer.Symlink,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.SymlinkRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.SymlinkResponse.SerializeToString,
            ),
            'FileCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileCreate,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileCreateRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileCreateResponse.SerializeToString,
            ),
            'FileCreateTemp': grpc.unary_unary_rpc_method_handler(
                    servicer.FileCreateTemp,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileCreateTempRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileCreateTempResponse.SerializeToString,
            ),
            'FileOpen': grpc.unary_unary_rpc_method_handler(
                    servicer.FileOpen,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileOpenRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileOpenResponse.SerializeToString,
            ),
            'FileStat': grpc.unary_unary_rpc_method_handler(
                    servicer.FileStat,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileStatRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileStatResponse.SerializeToString,
            ),
            'FileSeek': grpc.unary_unary_rpc_method_handler(
                    servicer.FileSeek,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileSeekRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileSeekResponse.SerializeToString,
            ),
            'FileSync': grpc.unary_unary_rpc_method_handler(
                    servicer.FileSync,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileSyncRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileSyncResponse.SerializeToString,
            ),
            'FileClose': grpc.unary_unary_rpc_method_handler(
                    servicer.FileClose,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileCloseRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileCloseResponse.SerializeToString,
            ),
            'FileTruncate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileTruncate,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileTruncateRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileTruncateResponse.SerializeToString,
            ),
            'FileChmod': grpc.unary_unary_rpc_method_handler(
                    servicer.FileChmod,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileChmodRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileChmodResponse.SerializeToString,
            ),
            'FileChown': grpc.unary_unary_rpc_method_handler(
                    servicer.FileChown,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileChownRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileChownResponse.SerializeToString,
            ),
            'FileReadSection': grpc.unary_unary_rpc_method_handler(
                    servicer.FileReadSection,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadSectionRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadSectionResponse.SerializeToString,
            ),
            'FileWriteSection': grpc.unary_unary_rpc_method_handler(
                    servicer.FileWriteSection,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteSectionRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteSectionResponse.SerializeToString,
            ),
            'FileReader': grpc.unary_stream_rpc_method_handler(
                    servicer.FileReader,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadResponse.SerializeToString,
            ),
            'FileReaderAt': grpc.unary_stream_rpc_method_handler(
                    servicer.FileReaderAt,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadAtRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileReadAtResponse.SerializeToString,
            ),
            'FileWriter': grpc.stream_unary_rpc_method_handler(
                    servicer.FileWriter,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteResponse.SerializeToString,
            ),
            'FileWriterAt': grpc.stream_unary_rpc_method_handler(
                    servicer.FileWriterAt,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteAtRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.FileWriteAtResponse.SerializeToString,
            ),
            'Getuid': grpc.unary_unary_rpc_method_handler(
                    servicer.Getuid,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetuidRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetuidResponse.SerializeToString,
            ),
            'Getgid': grpc.unary_unary_rpc_method_handler(
                    servicer.Getgid,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetgidRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetgidResponse.SerializeToString,
            ),
            'Geteuid': grpc.unary_unary_rpc_method_handler(
                    servicer.Geteuid,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GeteuidRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.GeteuidResponse.SerializeToString,
            ),
            'Getegid': grpc.unary_unary_rpc_method_handler(
                    servicer.Getegid,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetegidRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetegidResponse.SerializeToString,
            ),
            'GetGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroups,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetGroupsRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetGroupsResponse.SerializeToString,
            ),
            'Getpid': grpc.unary_unary_rpc_method_handler(
                    servicer.Getpid,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetpidRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetpidResponse.SerializeToString,
            ),
            'Getppid': grpc.unary_unary_rpc_method_handler(
                    servicer.Getppid,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetppidRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetppidResponse.SerializeToString,
            ),
            'GetEnv': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnv,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.GetEnvRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.GetEnvResponse.SerializeToString,
            ),
            'TempDir': grpc.unary_unary_rpc_method_handler(
                    servicer.TempDir,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.TempDirRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.TempDirResponse.SerializeToString,
            ),
            'UserCacheDir': grpc.unary_unary_rpc_method_handler(
                    servicer.UserCacheDir,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.UserCacheDirRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.UserCacheDirResponse.SerializeToString,
            ),
            'UserConfigDir': grpc.unary_unary_rpc_method_handler(
                    servicer.UserConfigDir,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.UserConfigDirRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.UserConfigDirResponse.SerializeToString,
            ),
            'UserHomeDir': grpc.unary_unary_rpc_method_handler(
                    servicer.UserHomeDir,
                    request_deserializer=hostserve_dot_v1_dot_hostserve__pb2.UserHomeDirRequest.FromString,
                    response_serializer=hostserve_dot_v1_dot_hostserve__pb2.UserHomeDirResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hostserve.v1.HostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hostserve.v1.HostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostService(object):
    """/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////Service Endpoints//////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    HostService is a service provided by the host process and is generally preferred over granting direct
    access to the plugin process
    """

    @staticmethod
    def ReadDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/ReadDir',
            hostserve_dot_v1_dot_hostserve__pb2.ReadDirRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.ReadDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/ReadFile',
            hostserve_dot_v1_dot_hostserve__pb2.ReadFileRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/WriteFile',
            hostserve_dot_v1_dot_hostserve__pb2.WriteFileRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Stat',
            hostserve_dot_v1_dot_hostserve__pb2.StatRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Rename',
            hostserve_dot_v1_dot_hostserve__pb2.RenameRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.RenameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Remove',
            hostserve_dot_v1_dot_hostserve__pb2.RemoveRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.RemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/RemoveAll',
            hostserve_dot_v1_dot_hostserve__pb2.RemoveAllRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.RemoveAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Mkdir',
            hostserve_dot_v1_dot_hostserve__pb2.MkdirRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.MkdirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MkdirAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/MkdirAll',
            hostserve_dot_v1_dot_hostserve__pb2.MkdirAllRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.MkdirAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MkdirTemp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/MkdirTemp',
            hostserve_dot_v1_dot_hostserve__pb2.MkdirTempRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.MkdirTempResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chmod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Chmod',
            hostserve_dot_v1_dot_hostserve__pb2.ChmodRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.ChmodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Chown',
            hostserve_dot_v1_dot_hostserve__pb2.ChownRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.ChownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chtimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Chtimes',
            hostserve_dot_v1_dot_hostserve__pb2.ChtimesRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.ChtimesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lchown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Lchown',
            hostserve_dot_v1_dot_hostserve__pb2.LchownRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.LchownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lstat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Lstat',
            hostserve_dot_v1_dot_hostserve__pb2.LstatRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.LstatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Readlink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Readlink',
            hostserve_dot_v1_dot_hostserve__pb2.ReadlinkRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.ReadlinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Link(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Link',
            hostserve_dot_v1_dot_hostserve__pb2.LinkRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.LinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Symlink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Symlink',
            hostserve_dot_v1_dot_hostserve__pb2.SymlinkRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.SymlinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileCreate',
            hostserve_dot_v1_dot_hostserve__pb2.FileCreateRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileCreateTemp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileCreateTemp',
            hostserve_dot_v1_dot_hostserve__pb2.FileCreateTempRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileCreateTempResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileOpen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileOpen',
            hostserve_dot_v1_dot_hostserve__pb2.FileOpenRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileOpenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileStat',
            hostserve_dot_v1_dot_hostserve__pb2.FileStatRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileSeek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileSeek',
            hostserve_dot_v1_dot_hostserve__pb2.FileSeekRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileSeekResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileSync',
            hostserve_dot_v1_dot_hostserve__pb2.FileSyncRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileClose',
            hostserve_dot_v1_dot_hostserve__pb2.FileCloseRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileCloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileTruncate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileTruncate',
            hostserve_dot_v1_dot_hostserve__pb2.FileTruncateRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileTruncateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileChmod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileChmod',
            hostserve_dot_v1_dot_hostserve__pb2.FileChmodRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileChmodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileChown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileChown',
            hostserve_dot_v1_dot_hostserve__pb2.FileChownRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileChownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileReadSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileReadSection',
            hostserve_dot_v1_dot_hostserve__pb2.FileReadSectionRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileReadSectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileWriteSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/FileWriteSection',
            hostserve_dot_v1_dot_hostserve__pb2.FileWriteSectionRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileWriteSectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileReader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hostserve.v1.HostService/FileReader',
            hostserve_dot_v1_dot_hostserve__pb2.FileReadRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileReaderAt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hostserve.v1.HostService/FileReaderAt',
            hostserve_dot_v1_dot_hostserve__pb2.FileReadAtRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileReadAtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileWriter(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/hostserve.v1.HostService/FileWriter',
            hostserve_dot_v1_dot_hostserve__pb2.FileWriteRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileWriterAt(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/hostserve.v1.HostService/FileWriterAt',
            hostserve_dot_v1_dot_hostserve__pb2.FileWriteAtRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.FileWriteAtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Getuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Getuid',
            hostserve_dot_v1_dot_hostserve__pb2.GetuidRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.GetuidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Getgid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Getgid',
            hostserve_dot_v1_dot_hostserve__pb2.GetgidRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.GetgidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Geteuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Geteuid',
            hostserve_dot_v1_dot_hostserve__pb2.GeteuidRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.GeteuidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Getegid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Getegid',
            hostserve_dot_v1_dot_hostserve__pb2.GetegidRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.GetegidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/GetGroups',
            hostserve_dot_v1_dot_hostserve__pb2.GetGroupsRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.GetGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Getpid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Getpid',
            hostserve_dot_v1_dot_hostserve__pb2.GetpidRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.GetpidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Getppid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/Getppid',
            hostserve_dot_v1_dot_hostserve__pb2.GetppidRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.GetppidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/GetEnv',
            hostserve_dot_v1_dot_hostserve__pb2.GetEnvRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.GetEnvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TempDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/TempDir',
            hostserve_dot_v1_dot_hostserve__pb2.TempDirRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.TempDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserCacheDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/UserCacheDir',
            hostserve_dot_v1_dot_hostserve__pb2.UserCacheDirRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.UserCacheDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserConfigDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/UserConfigDir',
            hostserve_dot_v1_dot_hostserve__pb2.UserConfigDirRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.UserConfigDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserHomeDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostserve.v1.HostService/UserHomeDir',
            hostserve_dot_v1_dot_hostserve__pb2.UserHomeDirRequest.SerializeToString,
            hostserve_dot_v1_dot_hostserve__pb2.UserHomeDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
