syntax = "proto3";
package hostdemo.v1;
option go_package = "github.com/bmj2728/HostServiceTest/shared/protogen/hostdemo/v1;hostdemov1";

service HostDemo {
  rpc EstablishHostServices(HostServiceRequest) returns (HostServiceResponse);
  rpc GetEnvDemo(GetEnvDemoReq) returns (GetEnvDemoResp);
  rpc EnvDemo(EnvDemoReq) returns (EnvDemoResp);
  rpc TempDemo(TempDemoReq) returns (TempDemoResp);
  rpc CreateDirFileDemo(CreateDemoReq) returns (CreateDemoResp);
  rpc ReadFrankenstein(ReadFrankensteinReq) returns (ReadFrankensteinResp);
}

message HostServiceRequest {
  uint32 host_service = 1;
}

message HostServiceResponse {
  string client_id = 1;
  optional string error = 2;
}

message GetEnvDemoReq {
  string key = 1;
}

message GetEnvDemoResp {
  string resp = 1;
  optional string error = 2;
}

message EnvDemoReq {
}

message EnvDemoResp {
  string resp = 1;
  optional string error = 2;
}

message TempDemoReq {
  string pattern = 1;
  string text_to_write = 2;
}

message TempDemoResp {
  string resp = 1;
  optional string error = 2;
}

message ReadFrankensteinReq {

}

message ReadFrankensteinResp {
  string frank = 1;
  optional string error = 2;
}

message CreateDemoReq {
  string dir_to_create = 1;
  string file_to_create = 2;
}

message CreateDemoResp {
  string demo_resp = 1;
  optional string error = 2;
}