# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hostdemo.v1 import hostdemo_pb2 as hostdemo_dot_v1_dot_hostdemo__pb2


class HostDemoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstablishHostServices = channel.unary_unary(
                '/hostdemo.v1.HostDemo/EstablishHostServices',
                request_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.HostServiceRequest.SerializeToString,
                response_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.HostServiceResponse.FromString,
                _registered_method=True)
        self.GetEnvDemo = channel.unary_unary(
                '/hostdemo.v1.HostDemo/GetEnvDemo',
                request_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.GetEnvDemoReq.SerializeToString,
                response_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.GetEnvDemoResp.FromString,
                _registered_method=True)
        self.EnvDemo = channel.unary_unary(
                '/hostdemo.v1.HostDemo/EnvDemo',
                request_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.EnvDemoReq.SerializeToString,
                response_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.EnvDemoResp.FromString,
                _registered_method=True)
        self.TempDemo = channel.unary_unary(
                '/hostdemo.v1.HostDemo/TempDemo',
                request_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.TempDemoReq.SerializeToString,
                response_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.TempDemoResp.FromString,
                _registered_method=True)
        self.ReadFrankenstein = channel.unary_unary(
                '/hostdemo.v1.HostDemo/ReadFrankenstein',
                request_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.ReadFrankensteinReq.SerializeToString,
                response_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.ReadFrankensteinResp.FromString,
                _registered_method=True)


class HostDemoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EstablishHostServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvDemo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnvDemo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TempDemo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFrankenstein(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostDemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstablishHostServices': grpc.unary_unary_rpc_method_handler(
                    servicer.EstablishHostServices,
                    request_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.HostServiceRequest.FromString,
                    response_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.HostServiceResponse.SerializeToString,
            ),
            'GetEnvDemo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvDemo,
                    request_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.GetEnvDemoReq.FromString,
                    response_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.GetEnvDemoResp.SerializeToString,
            ),
            'EnvDemo': grpc.unary_unary_rpc_method_handler(
                    servicer.EnvDemo,
                    request_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.EnvDemoReq.FromString,
                    response_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.EnvDemoResp.SerializeToString,
            ),
            'TempDemo': grpc.unary_unary_rpc_method_handler(
                    servicer.TempDemo,
                    request_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.TempDemoReq.FromString,
                    response_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.TempDemoResp.SerializeToString,
            ),
            'ReadFrankenstein': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFrankenstein,
                    request_deserializer=hostdemo_dot_v1_dot_hostdemo__pb2.ReadFrankensteinReq.FromString,
                    response_serializer=hostdemo_dot_v1_dot_hostdemo__pb2.ReadFrankensteinResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hostdemo.v1.HostDemo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hostdemo.v1.HostDemo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostDemo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EstablishHostServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostdemo.v1.HostDemo/EstablishHostServices',
            hostdemo_dot_v1_dot_hostdemo__pb2.HostServiceRequest.SerializeToString,
            hostdemo_dot_v1_dot_hostdemo__pb2.HostServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvDemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostdemo.v1.HostDemo/GetEnvDemo',
            hostdemo_dot_v1_dot_hostdemo__pb2.GetEnvDemoReq.SerializeToString,
            hostdemo_dot_v1_dot_hostdemo__pb2.GetEnvDemoResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnvDemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostdemo.v1.HostDemo/EnvDemo',
            hostdemo_dot_v1_dot_hostdemo__pb2.EnvDemoReq.SerializeToString,
            hostdemo_dot_v1_dot_hostdemo__pb2.EnvDemoResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TempDemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostdemo.v1.HostDemo/TempDemo',
            hostdemo_dot_v1_dot_hostdemo__pb2.TempDemoReq.SerializeToString,
            hostdemo_dot_v1_dot_hostdemo__pb2.TempDemoResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFrankenstein(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hostdemo.v1.HostDemo/ReadFrankenstein',
            hostdemo_dot_v1_dot_hostdemo__pb2.ReadFrankensteinReq.SerializeToString,
            hostdemo_dot_v1_dot_hostdemo__pb2.ReadFrankensteinResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
