# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hostdemo/v1/hostdemo.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'hostdemo/v1/hostdemo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ahostdemo/v1/hostdemo.proto\x12\x0bhostdemo.v1\"7\n\x12HostServiceRequest\x12!\n\x0chost_service\x18\x01 \x01(\rR\x0bhostService\"W\n\x13HostServiceResponse\x12\x1b\n\tclient_id\x18\x01 \x01(\tR\x08\x63lientId\x12\x19\n\x05\x65rror\x18\x02 \x01(\tH\x00R\x05\x65rror\x88\x01\x01\x42\x08\n\x06_error\"!\n\rGetEnvDemoReq\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\"I\n\x0eGetEnvDemoResp\x12\x12\n\x04resp\x18\x01 \x01(\tR\x04resp\x12\x19\n\x05\x65rror\x18\x02 \x01(\tH\x00R\x05\x65rror\x88\x01\x01\x42\x08\n\x06_error\"\x0c\n\nEnvDemoReq\"F\n\x0b\x45nvDemoResp\x12\x12\n\x04resp\x18\x01 \x01(\tR\x04resp\x12\x19\n\x05\x65rror\x18\x02 \x01(\tH\x00R\x05\x65rror\x88\x01\x01\x42\x08\n\x06_error\"K\n\x0bTempDemoReq\x12\x18\n\x07pattern\x18\x01 \x01(\tR\x07pattern\x12\"\n\rtext_to_write\x18\x02 \x01(\tR\x0btextToWrite\"G\n\x0cTempDemoResp\x12\x12\n\x04resp\x18\x01 \x01(\tR\x04resp\x12\x19\n\x05\x65rror\x18\x02 \x01(\tH\x00R\x05\x65rror\x88\x01\x01\x42\x08\n\x06_error2\xac\x02\n\x08HostDemo\x12Z\n\x15\x45stablishHostServices\x12\x1f.hostdemo.v1.HostServiceRequest\x1a .hostdemo.v1.HostServiceResponse\x12\x45\n\nGetEnvDemo\x12\x1a.hostdemo.v1.GetEnvDemoReq\x1a\x1b.hostdemo.v1.GetEnvDemoResp\x12<\n\x07\x45nvDemo\x12\x17.hostdemo.v1.EnvDemoReq\x1a\x18.hostdemo.v1.EnvDemoResp\x12?\n\x08TempDemo\x12\x18.hostdemo.v1.TempDemoReq\x1a\x19.hostdemo.v1.TempDemoRespB\xb8\x01\n\x0f\x63om.hostdemo.v1B\rHostdemoProtoP\x01ZIgithub.com/bmj2728/HostServiceTest/shared/protogen/hostdemo/v1;hostdemov1\xa2\x02\x03HXX\xaa\x02\x0bHostdemo.V1\xca\x02\x0bHostdemo\\V1\xe2\x02\x17Hostdemo\\V1\\GPBMetadata\xea\x02\x0cHostdemo::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hostdemo.v1.hostdemo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.hostdemo.v1B\rHostdemoProtoP\001ZIgithub.com/bmj2728/HostServiceTest/shared/protogen/hostdemo/v1;hostdemov1\242\002\003HXX\252\002\013Hostdemo.V1\312\002\013Hostdemo\\V1\342\002\027Hostdemo\\V1\\GPBMetadata\352\002\014Hostdemo::V1'
  _globals['_HOSTSERVICEREQUEST']._serialized_start=43
  _globals['_HOSTSERVICEREQUEST']._serialized_end=98
  _globals['_HOSTSERVICERESPONSE']._serialized_start=100
  _globals['_HOSTSERVICERESPONSE']._serialized_end=187
  _globals['_GETENVDEMOREQ']._serialized_start=189
  _globals['_GETENVDEMOREQ']._serialized_end=222
  _globals['_GETENVDEMORESP']._serialized_start=224
  _globals['_GETENVDEMORESP']._serialized_end=297
  _globals['_ENVDEMOREQ']._serialized_start=299
  _globals['_ENVDEMOREQ']._serialized_end=311
  _globals['_ENVDEMORESP']._serialized_start=313
  _globals['_ENVDEMORESP']._serialized_end=383
  _globals['_TEMPDEMOREQ']._serialized_start=385
  _globals['_TEMPDEMOREQ']._serialized_end=460
  _globals['_TEMPDEMORESP']._serialized_start=462
  _globals['_TEMPDEMORESP']._serialized_end=533
  _globals['_HOSTDEMO']._serialized_start=536
  _globals['_HOSTDEMO']._serialized_end=836
# @@protoc_insertion_point(module_scope)
